// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Represents a hardware accelerator type.
///
/// - Note: Adding cases to this enumeration is not considered a breaking change.
///   Always include an `@unknown default:` case when switching over this type.
///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
///   expecting specific values to remain unparsed; future releases may promote
///   them to named cases.
public enum AcceleratorType: Codable, Equatable, Hashable, Sendable {
  /// Unspecified accelerator type, which means no accelerator.
  case unspecified
  /// Nvidia Tesla K80 GPU.
  case nvidiaTeslaK80
  /// Nvidia Tesla P100 GPU.
  case nvidiaTeslaP100
  /// Nvidia Tesla V100 GPU.
  case nvidiaTeslaV100
  /// Nvidia Tesla P4 GPU.
  case nvidiaTeslaP4
  /// Nvidia Tesla T4 GPU.
  case nvidiaTeslaT4
  /// TPU v2.
  case tpuV2
  /// TPU v3.
  case tpuV3
  /// Nvidia Tesla A100 GPU.
  case nvidiaTeslaA100
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific integer values in this case;
  ///   future releases may promote them to named enum cases.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific string literals in this case;
  ///   future releases may promote them to named enum cases.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .nvidiaTeslaK80: return 1
    case .nvidiaTeslaP100: return 2
    case .nvidiaTeslaV100: return 3
    case .nvidiaTeslaP4: return 4
    case .nvidiaTeslaT4: return 5
    case .tpuV2: return 6
    case .tpuV3: return 7
    case .nvidiaTeslaA100: return 8
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "ACCELERATOR_TYPE_UNSPECIFIED"
    case .nvidiaTeslaK80: return "NVIDIA_TESLA_K80"
    case .nvidiaTeslaP100: return "NVIDIA_TESLA_P100"
    case .nvidiaTeslaV100: return "NVIDIA_TESLA_V100"
    case .nvidiaTeslaP4: return "NVIDIA_TESLA_P4"
    case .nvidiaTeslaT4: return "NVIDIA_TESLA_T4"
    case .tpuV2: return "TPU_V2"
    case .tpuV3: return "TPU_V3"
    case .nvidiaTeslaA100: return "NVIDIA_TESLA_A100"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AcceleratorType/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "ACCELERATOR_TYPE_UNSPECIFIED": self = .unspecified
    case "NVIDIA_TESLA_K80": self = .nvidiaTeslaK80
    case "NVIDIA_TESLA_P100": self = .nvidiaTeslaP100
    case "NVIDIA_TESLA_V100": self = .nvidiaTeslaV100
    case "NVIDIA_TESLA_P4": self = .nvidiaTeslaP4
    case "NVIDIA_TESLA_T4": self = .nvidiaTeslaT4
    case "NVIDIA_TESLA_A100": self = .nvidiaTeslaA100
    case "TPU_V2": self = .tpuV2
    case "TPU_V3": self = .tpuV3
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AcceleratorType/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .nvidiaTeslaK80
    case 2: self = .nvidiaTeslaP100
    case 3: self = .nvidiaTeslaV100
    case 4: self = .nvidiaTeslaP4
    case 5: self = .nvidiaTeslaT4
    case 6: self = .tpuV2
    case 7: self = .tpuV3
    case 8: self = .nvidiaTeslaA100
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode("ACCELERATOR_TYPE_UNSPECIFIED")
    case .nvidiaTeslaK80: return try container.encode("NVIDIA_TESLA_K80")
    case .nvidiaTeslaP100: return try container.encode("NVIDIA_TESLA_P100")
    case .nvidiaTeslaV100: return try container.encode("NVIDIA_TESLA_V100")
    case .nvidiaTeslaP4: return try container.encode("NVIDIA_TESLA_P4")
    case .nvidiaTeslaT4: return try container.encode("NVIDIA_TESLA_T4")
    case .tpuV2: return try container.encode("TPU_V2")
    case .tpuV3: return try container.encode("TPU_V3")
    case .nvidiaTeslaA100: return try container.encode("NVIDIA_TESLA_A100")
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
