// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Defines an Analyzer.
///
/// An analyzer processes data from its input streams using the logic defined in
/// the Operator that it represents. Of course, it produces data for the output
/// streams declared in the Operator.
public struct AnalyzerDefinition: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The name of this analyzer.
  ///
  /// Tentatively [a-z][a-z0-9]*(_[a-z0-9]+)*.
  public var analyzer: Swift.String = Swift.String()

  /// The name of the operator that this analyzer runs.
  ///
  /// Must match the name of a supported operator.
  public var `operator`: Swift.String = Swift.String()

  /// Input streams.
  public var inputs: [AnalyzerDefinition.StreamInput] = []

  /// The attribute values that this analyzer applies to the operator.
  ///
  /// Supply a mapping between the attribute names and the actual value you wish
  /// to apply. If an attribute name is omitted, then it will take a
  /// preconfigured default value.
  public var attrs: [Swift.String: AttributeValue] = [:]

  /// Debug options.
  public var debugOptions: AnalyzerDefinition.DebugOptions? = nil

  /// Operator option.
  public var operatorOption: AnalyzerDefinition.OperatorOption? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AnalyzerDefinition`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AnalyzerDefinition().with { $0.analyzer = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let analyzer = CodingKeys(stringValue: "analyzer")
    static let `operator` = CodingKeys(stringValue: "operator")
    static let inputs = CodingKeys(stringValue: "inputs")
    static let attrs = CodingKeys(stringValue: "attrs")
    static let debugOptions = CodingKeys(stringValue: "debugOptions")
    static let operatorOption = CodingKeys(stringValue: "operatorOption")

    static let _knownKeys: Set<Swift.String> = [
      "analyzer",
      "operator",
      "inputs",
      "attrs",
      "debugOptions",
      "operatorOption",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .analyzer) {
      self.analyzer = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .`operator`) {
      self.`operator` = value
    }
    if let value = try container.decodeIfPresent(
      [AnalyzerDefinition.StreamInput].self, forKey: .inputs)
    {
      self.inputs = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: AttributeValue].self, forKey: .attrs)
    {
      self.attrs = value
    }
    self.debugOptions = try container.decodeIfPresent(
      AnalyzerDefinition.DebugOptions.self, forKey: .debugOptions)
    self.operatorOption = try container.decodeIfPresent(
      AnalyzerDefinition.OperatorOption.self, forKey: .operatorOption)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.analyzer, forKey: .analyzer)
    try container.encode(self.`operator`, forKey: .`operator`)
    try container.encode(self.inputs, forKey: .inputs)
    try container.encode(self.attrs, forKey: .attrs)
    try container.encodeIfPresent(self.debugOptions, forKey: .debugOptions)
    try container.encodeIfPresent(self.operatorOption, forKey: .operatorOption)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The inputs to this analyzer.
  ///
  /// We accept input name references of the following form:
  /// <analyzer-name>:<output-argument-name>
  ///
  /// Example:
  ///
  /// Suppose you had an operator named "SomeOp" that has 2 output
  /// arguments, the first of which is named "foo" and the second of which is
  /// named "bar", and an operator named "MyOp" that accepts 2 inputs.
  ///
  /// Also suppose that there is an analyzer named "some-analyzer" that is
  /// running "SomeOp" and another analyzer named "my-analyzer" running "MyOp".
  ///
  /// To indicate that "my-analyzer" is to consume "some-analyzer"'s "foo"
  /// output as its first input and "some-analyzer"'s "bar" output as its
  /// second input, you can set this field to the following:
  /// input = ["some-analyzer:foo", "some-analyzer:bar"]
  public struct StreamInput: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The name of the stream input (as discussed above).
    public var input: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `StreamInput`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = StreamInput().with { $0.input = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let input = CodingKeys(stringValue: "input")

      static let _knownKeys: Set<Swift.String> = [
        "input"
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .input) {
        self.input = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.input, forKey: .input)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.AnalyzerDefinition.StreamInput"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Options available for debugging purposes only.
  public struct DebugOptions: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Environment variables.
    public var environmentVariables: [Swift.String: Swift.String] = [:]

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `DebugOptions`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DebugOptions().with { $0.environmentVariables = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let environmentVariables = CodingKeys(stringValue: "environmentVariables")

      static let _knownKeys: Set<Swift.String> = [
        "environmentVariables"
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        [Swift.String: Swift.String].self, forKey: .environmentVariables)
      {
        self.environmentVariables = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.environmentVariables, forKey: .environmentVariables)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.AnalyzerDefinition.DebugOptions"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Option related to the operator.
  public struct OperatorOption: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Tag of the operator.
    public var tag: Swift.String = Swift.String()

    /// Registry of the operator. e.g. public, dev.
    public var registry: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `OperatorOption`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = OperatorOption().with { $0.tag = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let tag = CodingKeys(stringValue: "tag")
      static let registry = CodingKeys(stringValue: "registry")

      static let _knownKeys: Set<Swift.String> = [
        "tag",
        "registry",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .tag) {
        self.tag = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .registry) {
        self.registry = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.tag, forKey: .tag)
      try container.encode(self.registry, forKey: .registry)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.AnalyzerDefinition.OperatorOption"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.AnalyzerDefinition"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
