// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Value of annotation, including all types available in data schema.
public struct AnnotationValue: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  public var value: ValueOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AnnotationValue`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AnnotationValue().with { $0.intValue = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let intValue = CodingKeys(stringValue: "intValue")
    static let floatValue = CodingKeys(stringValue: "floatValue")
    static let strValue = CodingKeys(stringValue: "strValue")
    static let datetimeValue = CodingKeys(stringValue: "datetimeValue")
    static let geoCoordinate = CodingKeys(stringValue: "geoCoordinate")
    static let protoAnyValue = CodingKeys(stringValue: "protoAnyValue")
    static let boolValue = CodingKeys(stringValue: "boolValue")
    static let customizedStructDataValue = CodingKeys(stringValue: "customizedStructDataValue")
    static let listValue = CodingKeys(stringValue: "listValue")
    static let customizedStructValue = CodingKeys(stringValue: "customizedStructValue")

    static let _knownKeys: Set<Swift.String> = [
      "intValue",
      "floatValue",
      "strValue",
      "datetimeValue",
      "geoCoordinate",
      "protoAnyValue",
      "boolValue",
      "customizedStructDataValue",
      "listValue",
      "customizedStructValue",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var value: ValueOneOf? = nil
    let valueCheckAndSet = {
      if value != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'value'"))
      }
      value = $0
    }
    if let intValue = try container.decodeIfPresent(Swift.Int64.self, forKey: .intValue) {
      try valueCheckAndSet(.intValue(intValue))
    }
    if let floatValue = try container.decodeIfPresent(Swift.Float.self, forKey: .floatValue) {
      try valueCheckAndSet(.floatValue(floatValue))
    }
    if let strValue = try container.decodeIfPresent(Swift.String.self, forKey: .strValue) {
      try valueCheckAndSet(.strValue(strValue))
    }
    if let datetimeValue = try container.decodeIfPresent(Swift.String.self, forKey: .datetimeValue)
    {
      try valueCheckAndSet(.datetimeValue(datetimeValue))
    }
    if let geoCoordinate = try container.decodeIfPresent(GeoCoordinate.self, forKey: .geoCoordinate)
    {
      try valueCheckAndSet(.geoCoordinate(geoCoordinate))
    }
    if let protoAnyValue = try container.decodeIfPresent(
      GoogleWKT.WKTAny.self, forKey: .protoAnyValue)
    {
      try valueCheckAndSet(.protoAnyValue(protoAnyValue))
    }
    if let boolValue = try container.decodeIfPresent(Swift.Bool.self, forKey: .boolValue) {
      try valueCheckAndSet(.boolValue(boolValue))
    }
    if let customizedStructDataValue = try container.decodeIfPresent(
      GoogleWKT.WKTStruct.self, forKey: .customizedStructDataValue)
    {
      try valueCheckAndSet(.customizedStructDataValue(customizedStructDataValue))
    }
    if let listValue = try container.decodeIfPresent(AnnotationList.self, forKey: .listValue) {
      try valueCheckAndSet(.listValue(listValue))
    }
    if let customizedStructValue = try container.decodeIfPresent(
      AnnotationCustomizedStruct.self, forKey: .customizedStructValue)
    {
      try valueCheckAndSet(.customizedStructValue(customizedStructValue))
    }
    self.value = value
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.value {
      switch choice {
      case .intValue(let value):
        try container.encode(value, forKey: .intValue)
      case .floatValue(let value):
        try container.encode(value, forKey: .floatValue)
      case .strValue(let value):
        try container.encode(value, forKey: .strValue)
      case .datetimeValue(let value):
        try container.encode(value, forKey: .datetimeValue)
      case .geoCoordinate(let value):
        try container.encode(value, forKey: .geoCoordinate)
      case .protoAnyValue(let value):
        try container.encode(value, forKey: .protoAnyValue)
      case .boolValue(let value):
        try container.encode(value, forKey: .boolValue)
      case .customizedStructDataValue(let value):
        try container.encode(value, forKey: .customizedStructDataValue)
      case .listValue(let value):
        try container.encode(value, forKey: .listValue)
      case .customizedStructValue(let value):
        try container.encode(value, forKey: .customizedStructValue)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public enum ValueOneOf: Codable, Equatable, Sendable {
    /// Value of int type annotation.
    case intValue(Swift.Int64)
    /// Value of float type annotation.
    case floatValue(Swift.Float)
    /// Value of string type annotation.
    case strValue(Swift.String)
    /// Value of date time type annotation.
    case datetimeValue(Swift.String)
    /// Value of geo coordinate type annotation.
    indirect case geoCoordinate(GeoCoordinate)
    /// Value of any proto value.
    indirect case protoAnyValue(GoogleWKT.WKTAny)
    /// Value of boolean type annotation.
    case boolValue(Swift.Bool)
    /// Value of customized struct annotation. This field does not have effects.
    /// Use customized_struct_value instead for customized struct annotation.
    indirect case customizedStructDataValue(GoogleWKT.WKTStruct)
    /// Value of list type annotation.
    indirect case listValue(AnnotationList)
    /// Value of custom struct type annotation.
    indirect case customizedStructValue(AnnotationCustomizedStruct)
  }

  /// The type URL for `AnnotationValue`: `"type.googleapis.com/google.cloud.visionai.v1.AnnotationValue"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.AnnotationValue"
  }

  /// Initialize an instance of `AnnotationValue` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.visionai.v1.AnnotationValue"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `AnnotationValue` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
