// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// For any cloud function based customer processing logic, customer's cloud
/// function is expected to receive AppPlatformCloudFunctionRequest as request
/// and send back AppPlatformCloudFunctionResponse as response.
/// Message of request from AppPlatform to Cloud Function.
public struct AppPlatformCloudFunctionRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The metadata of the AppPlatform for customer to identify the source of the
  /// payload.
  public var appPlatformMetadata: AppPlatformMetadata? = nil

  /// The actual annotations to be processed by the customized Cloud Function.
  public var annotations: [AppPlatformCloudFunctionRequest.StructedInputAnnotation] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AppPlatformCloudFunctionRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AppPlatformCloudFunctionRequest().with { $0.appPlatformMetadata = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let appPlatformMetadata = CodingKeys(stringValue: "appPlatformMetadata")
    static let annotations = CodingKeys(stringValue: "annotations")

    static let _knownKeys: Set<Swift.String> = [
      "appPlatformMetadata",
      "annotations",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.appPlatformMetadata = try container.decodeIfPresent(
      AppPlatformMetadata.self, forKey: .appPlatformMetadata)
    if let value = try container.decodeIfPresent(
      [AppPlatformCloudFunctionRequest.StructedInputAnnotation].self, forKey: .annotations)
    {
      self.annotations = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.appPlatformMetadata, forKey: .appPlatformMetadata)
    try container.encode(self.annotations, forKey: .annotations)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// A general annotation message that uses struct format to represent different
  /// concrete annotation protobufs.
  public struct StructedInputAnnotation: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The ingestion time of the current annotation.
    public var ingestionTimeMicros: Swift.Int64 = Swift.Int64()

    /// The struct format of the actual annotation.
    public var annotation: GoogleWKT.WKTStruct? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `StructedInputAnnotation`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = StructedInputAnnotation().with { $0.ingestionTimeMicros = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let ingestionTimeMicros = CodingKeys(stringValue: "ingestionTimeMicros")
      static let annotation = CodingKeys(stringValue: "annotation")

      static let _knownKeys: Set<Swift.String> = [
        "ingestionTimeMicros",
        "annotation",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .ingestionTimeMicros) {
        self.ingestionTimeMicros = value
      }
      self.annotation = try container.decodeIfPresent(GoogleWKT.WKTStruct.self, forKey: .annotation)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.ingestionTimeMicros, forKey: .ingestionTimeMicros)
      try container.encodeIfPresent(self.annotation, forKey: .annotation)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.visionai.v1.AppPlatformCloudFunctionRequest.StructedInputAnnotation"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.AppPlatformCloudFunctionRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
