// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Message of the response from customer's Cloud Function to AppPlatform.
public struct AppPlatformCloudFunctionResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The modified annotations that is returned back to AppPlatform.
  /// If the annotations fields are empty, then those annotations will be dropped
  /// by AppPlatform.
  public var annotations: [AppPlatformCloudFunctionResponse.StructedOutputAnnotation] = []

  /// If set to true, AppPlatform will use original annotations instead of
  /// dropping them, even if it is empty in the annotations filed.
  public var annotationPassthrough: Swift.Bool = Swift.Bool()

  /// The event notifications that is returned back to AppPlatform. Typically it
  /// will then be configured to be consumed/forwared to a operator that handles
  /// events, such as Pub/Sub operator.
  public var events: [AppPlatformEventBody] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AppPlatformCloudFunctionResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AppPlatformCloudFunctionResponse().with { $0.annotations = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let annotations = CodingKeys(stringValue: "annotations")
    static let annotationPassthrough = CodingKeys(stringValue: "annotationPassthrough")
    static let events = CodingKeys(stringValue: "events")

    static let _knownKeys: Set<Swift.String> = [
      "annotations",
      "annotationPassthrough",
      "events",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [AppPlatformCloudFunctionResponse.StructedOutputAnnotation].self, forKey: .annotations)
    {
      self.annotations = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .annotationPassthrough) {
      self.annotationPassthrough = value
    }
    if let value = try container.decodeIfPresent([AppPlatformEventBody].self, forKey: .events) {
      self.events = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.annotations, forKey: .annotations)
    try container.encode(self.annotationPassthrough, forKey: .annotationPassthrough)
    try container.encode(self.events, forKey: .events)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// A general annotation message that uses struct format to represent different
  /// concrete annotation protobufs.
  public struct StructedOutputAnnotation: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The struct format of the actual annotation.
    public var annotation: GoogleWKT.WKTStruct? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `StructedOutputAnnotation`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = StructedOutputAnnotation().with { $0.annotation = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let annotation = CodingKeys(stringValue: "annotation")

      static let _knownKeys: Set<Swift.String> = [
        "annotation"
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.annotation = try container.decodeIfPresent(GoogleWKT.WKTStruct.self, forKey: .annotation)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.annotation, forKey: .annotation)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.visionai.v1.AppPlatformCloudFunctionResponse.StructedOutputAnnotation"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.AppPlatformCloudFunctionResponse"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
