// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Corpus is a set of media contents for management.
/// Within a corpus, media shares the same data schema. Search is also restricted
/// within a single corpus.
public struct Corpus: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Resource name of the corpus.
  /// Format:
  /// `projects/{project_number}/locations/{location_id}/corpora/{corpus_id}`
  public var name: Swift.String = Swift.String()

  /// Required. The corpus name to shown in the UI. The name can be up to 32
  /// characters long.
  public var displayName: Swift.String = Swift.String()

  /// Optional. Description of the corpus. Can be up to 25000 characters long.
  public var description: Swift.String = Swift.String()

  /// Optional. The default TTL value for all assets under the corpus without a
  /// asset level user-defined TTL. For STREAM_VIDEO type corpora, this is
  /// required and the maximum allowed
  ///   default_ttl is 10 years.
  public var defaultTtl: GoogleWKT.WKTDuration? = nil

  /// Optional. Type of the asset inside corpus.
  public var type: Corpus.Type_ = Corpus.Type_()

  /// Default search capability setting on corpus level.
  public var searchCapabilitySetting: SearchCapabilitySetting? = nil

  /// Output only. This boolean field is only set for projects that have Physical
  /// Zone Separation enabled via an Org Policy constraint. It is set to true
  /// when the corpus is a valid zone separated corpus and false if it isn't.
  public var satisfiesPzs: Swift.Bool? = nil

  /// Output only. This boolean field is only set for projects that have Physical
  /// Zone Isolation enabled via an Org Policy constraint. It is set to true when
  /// the corpus is a valid zone isolated corpus and false if it isn't.
  public var satisfiesPzi: Swift.Bool? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Corpus`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Corpus().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let description = CodingKeys(stringValue: "description")
    static let defaultTtl = CodingKeys(stringValue: "defaultTtl")
    static let type = CodingKeys(stringValue: "type")
    static let searchCapabilitySetting = CodingKeys(stringValue: "searchCapabilitySetting")
    static let satisfiesPzs = CodingKeys(stringValue: "satisfiesPzs")
    static let satisfiesPzi = CodingKeys(stringValue: "satisfiesPzi")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "description",
      "defaultTtl",
      "type",
      "searchCapabilitySetting",
      "satisfiesPzs",
      "satisfiesPzi",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    self.defaultTtl = try container.decodeIfPresent(GoogleWKT.WKTDuration.self, forKey: .defaultTtl)
    if let value = try container.decodeIfPresent(Corpus.Type_.self, forKey: .type) {
      self.type = value
    }
    self.searchCapabilitySetting = try container.decodeIfPresent(
      SearchCapabilitySetting.self, forKey: .searchCapabilitySetting)
    self.satisfiesPzs = try container.decodeIfPresent(Swift.Bool.self, forKey: .satisfiesPzs)
    self.satisfiesPzi = try container.decodeIfPresent(Swift.Bool.self, forKey: .satisfiesPzi)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.description, forKey: .description)
    try container.encodeIfPresent(self.defaultTtl, forKey: .defaultTtl)
    try container.encode(self.type, forKey: .type)
    try container.encodeIfPresent(self.searchCapabilitySetting, forKey: .searchCapabilitySetting)
    try container.encodeIfPresent(self.satisfiesPzs, forKey: .satisfiesPzs)
    try container.encodeIfPresent(self.satisfiesPzi, forKey: .satisfiesPzi)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Type of the asset inside the corpus.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Type_: Codable, Equatable, Hashable, Sendable {
    /// The default type, not supposed to be used. If this default type is used,
    /// the corpus will be created as STREAM_VIDEO corpus.
    case unspecified
    /// Asset is a live streaming video.
    case streamVideo
    /// Asset is an image.
    case image
    /// Asset is a batch video.
    case videoOnDemand
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .streamVideo: return 1
      case .image: return 2
      case .videoOnDemand: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TYPE_UNSPECIFIED"
      case .streamVideo: return "STREAM_VIDEO"
      case .image: return "IMAGE"
      case .videoOnDemand: return "VIDEO_ON_DEMAND"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TYPE_UNSPECIFIED": self = .unspecified
      case "STREAM_VIDEO": self = .streamVideo
      case "IMAGE": self = .image
      case "VIDEO_ON_DEMAND": self = .videoOnDemand
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .streamVideo
      case 2: self = .image
      case 3: self = .videoOnDemand
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("TYPE_UNSPECIFIED")
      case .streamVideo: return try container.encode("STREAM_VIDEO")
      case .image: return try container.encode("IMAGE")
      case .videoOnDemand: return try container.encode("VIDEO_ON_DEMAND")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The type URL for `Corpus`: `"type.googleapis.com/google.cloud.visionai.v1.Corpus"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.Corpus"
  }

  /// Initialize an instance of `Corpus` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.visionai.v1.Corpus"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `Corpus` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
