// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Describes the source info for a custom processor.
public struct CustomProcessorSourceInfo: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The original product which holds the custom processor's functionality.
  public var sourceType: CustomProcessorSourceInfo.SourceType =
    CustomProcessorSourceInfo.SourceType()

  /// Output only. Additional info related to the imported custom processor.
  /// Data is filled in by app platform during the processor creation.
  public var additionalInfo: [Swift.String: Swift.String] = [:]

  /// Model schema files which specifies the signature of the model.
  /// For VERTEX_CUSTOM models, instances schema is required.
  /// If instances schema is not specified during the processor creation,
  /// VisionAI Platform will try to get it from Vertex, if it doesn't exist, the
  /// creation will fail.
  public var modelSchema: CustomProcessorSourceInfo.ModelSchema? = nil

  /// The path where App Platform loads the artifacts for the custom processor.
  public var artifactPath: ArtifactPathOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CustomProcessorSourceInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CustomProcessorSourceInfo().with { $0.vertexModel = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let vertexModel = CodingKeys(stringValue: "vertexModel")
    static let productRecognizerArtifact = CodingKeys(stringValue: "productRecognizerArtifact")
    static let sourceType = CodingKeys(stringValue: "sourceType")
    static let additionalInfo = CodingKeys(stringValue: "additionalInfo")
    static let modelSchema = CodingKeys(stringValue: "modelSchema")

    static let _knownKeys: Set<Swift.String> = [
      "vertexModel",
      "productRecognizerArtifact",
      "sourceType",
      "additionalInfo",
      "modelSchema",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      CustomProcessorSourceInfo.SourceType.self, forKey: .sourceType)
    {
      self.sourceType = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .additionalInfo)
    {
      self.additionalInfo = value
    }
    self.modelSchema = try container.decodeIfPresent(
      CustomProcessorSourceInfo.ModelSchema.self, forKey: .modelSchema)

    var artifactPath: ArtifactPathOneOf? = nil
    let artifactPathCheckAndSet = {
      if artifactPath != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'artifactPath'"))
      }
      artifactPath = $0
    }
    if let vertexModel = try container.decodeIfPresent(Swift.String.self, forKey: .vertexModel) {
      try artifactPathCheckAndSet(.vertexModel(vertexModel))
    }
    if let productRecognizerArtifact = try container.decodeIfPresent(
      CustomProcessorSourceInfo.ProductRecognizerArtifact.self, forKey: .productRecognizerArtifact)
    {
      try artifactPathCheckAndSet(.productRecognizerArtifact(productRecognizerArtifact))
    }
    self.artifactPath = artifactPath
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.sourceType, forKey: .sourceType)
    try container.encode(self.additionalInfo, forKey: .additionalInfo)
    try container.encodeIfPresent(self.modelSchema, forKey: .modelSchema)

    if let choice = self.artifactPath {
      switch choice {
      case .vertexModel(let value):
        try container.encode(value, forKey: .vertexModel)
      case .productRecognizerArtifact(let value):
        try container.encode(value, forKey: .productRecognizerArtifact)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Message describes product recognizer artifact.
  public struct ProductRecognizerArtifact: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. Resource name of RetailProductRecognitionIndex.
    /// Format is
    /// 'projects/*/locations/*/retailCatalogs/*/retailProductRecognitionIndexes/*'
    public var retailProductRecognitionIndex: Swift.String = Swift.String()

    /// Optional. The resource name of embedding model hosted in Vertex AI
    /// Platform.
    public var vertexModel: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ProductRecognizerArtifact`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ProductRecognizerArtifact().with { $0.retailProductRecognitionIndex = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let retailProductRecognitionIndex = CodingKeys(
        stringValue: "retailProductRecognitionIndex")
      static let vertexModel = CodingKeys(stringValue: "vertexModel")

      static let _knownKeys: Set<Swift.String> = [
        "retailProductRecognitionIndex",
        "vertexModel",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        Swift.String.self, forKey: .retailProductRecognitionIndex)
      {
        self.retailProductRecognitionIndex = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .vertexModel) {
        self.vertexModel = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(
        self.retailProductRecognitionIndex, forKey: .retailProductRecognitionIndex)
      try container.encode(self.vertexModel, forKey: .vertexModel)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.visionai.v1.CustomProcessorSourceInfo.ProductRecognizerArtifact"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The schema is defined as an OpenAPI 3.0.2 [Schema
  /// Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md#schemaObject).
  public struct ModelSchema: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Cloud Storage location to a YAML file that defines the format of a single
    /// instance used in prediction and explanation requests.
    public var instancesSchema: GcsSource? = nil

    /// Cloud Storage location to a YAML file that defines the prediction and
    /// explanation parameters.
    public var parametersSchema: GcsSource? = nil

    /// Cloud Storage location to a YAML file that defines the format of a single
    /// prediction or explanation.
    public var predictionsSchema: GcsSource? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ModelSchema`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ModelSchema().with { $0.instancesSchema = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let instancesSchema = CodingKeys(stringValue: "instancesSchema")
      static let parametersSchema = CodingKeys(stringValue: "parametersSchema")
      static let predictionsSchema = CodingKeys(stringValue: "predictionsSchema")

      static let _knownKeys: Set<Swift.String> = [
        "instancesSchema",
        "parametersSchema",
        "predictionsSchema",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.instancesSchema = try container.decodeIfPresent(GcsSource.self, forKey: .instancesSchema)
      self.parametersSchema = try container.decodeIfPresent(
        GcsSource.self, forKey: .parametersSchema)
      self.predictionsSchema = try container.decodeIfPresent(
        GcsSource.self, forKey: .predictionsSchema)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.instancesSchema, forKey: .instancesSchema)
      try container.encodeIfPresent(self.parametersSchema, forKey: .parametersSchema)
      try container.encodeIfPresent(self.predictionsSchema, forKey: .predictionsSchema)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.CustomProcessorSourceInfo.ModelSchema"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Source type of the imported custom processor.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum SourceType: Codable, Equatable, Hashable, Sendable {
    /// Source type unspecified.
    case unspecified
    /// Custom processors coming from Vertex AutoML product.
    case vertexAutoml
    /// Custom processors coming from general custom models from Vertex.
    case vertexCustom
    /// Source for Product Recognizer.
    case productRecognizer
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .vertexAutoml: return 1
      case .vertexCustom: return 2
      case .productRecognizer: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SOURCE_TYPE_UNSPECIFIED"
      case .vertexAutoml: return "VERTEX_AUTOML"
      case .vertexCustom: return "VERTEX_CUSTOM"
      case .productRecognizer: return "PRODUCT_RECOGNIZER"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SourceType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SOURCE_TYPE_UNSPECIFIED": self = .unspecified
      case "VERTEX_AUTOML": self = .vertexAutoml
      case "VERTEX_CUSTOM": self = .vertexCustom
      case "PRODUCT_RECOGNIZER": self = .productRecognizer
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SourceType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .vertexAutoml
      case 2: self = .vertexCustom
      case 3: self = .productRecognizer
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("SOURCE_TYPE_UNSPECIFIED")
      case .vertexAutoml: return try container.encode("VERTEX_AUTOML")
      case .vertexCustom: return try container.encode("VERTEX_CUSTOM")
      case .productRecognizer: return try container.encode("PRODUCT_RECOGNIZER")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The path where App Platform loads the artifacts for the custom processor.
  public enum ArtifactPathOneOf: Codable, Equatable, Sendable {
    /// The resource name original model hosted in the vertex AI platform.
    case vertexModel(Swift.String)
    /// Artifact for product recognizer.
    indirect case productRecognizerArtifact(CustomProcessorSourceInfo.ProductRecognizerArtifact)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.CustomProcessorSourceInfo"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
