// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Data schema details indicates the data type and the data struct corresponding
/// to the key of user specified annotation.
public struct DataSchemaDetails: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Type of the annotation.
  public var type: DataSchemaDetails.DataType? = nil

  /// Config for protobuf any type.
  public var protoAnyConfig: DataSchemaDetails.ProtoAnyConfig? = nil

  /// Config for List data type.
  public var listConfig: GoogleWKT.WKTRecursive<DataSchemaDetails.ListConfig>? = nil

  /// Config for CustomizedStruct data type.
  public var customizedStructConfig:
    GoogleWKT.WKTRecursive<DataSchemaDetails.CustomizedStructConfig>? = nil

  /// The granularity associated with this DataSchema.
  public var granularity: DataSchemaDetails.Granularity? = nil

  /// The search strategy to be applied on the `key` above.
  public var searchStrategy: DataSchemaDetails.SearchStrategy? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DataSchemaDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataSchemaDetails().with { $0.type = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let type = CodingKeys(stringValue: "type")
    static let protoAnyConfig = CodingKeys(stringValue: "protoAnyConfig")
    static let listConfig = CodingKeys(stringValue: "listConfig")
    static let customizedStructConfig = CodingKeys(stringValue: "customizedStructConfig")
    static let granularity = CodingKeys(stringValue: "granularity")
    static let searchStrategy = CodingKeys(stringValue: "searchStrategy")

    static let _knownKeys: Set<Swift.String> = [
      "type",
      "protoAnyConfig",
      "listConfig",
      "customizedStructConfig",
      "granularity",
      "searchStrategy",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.type = try container.decodeIfPresent(DataSchemaDetails.DataType.self, forKey: .type)
    self.protoAnyConfig = try container.decodeIfPresent(
      DataSchemaDetails.ProtoAnyConfig.self, forKey: .protoAnyConfig)
    self.listConfig = try container.decodeIfPresent(
      GoogleWKT.WKTRecursive<DataSchemaDetails.ListConfig>.self, forKey: .listConfig)
    self.customizedStructConfig = try container.decodeIfPresent(
      GoogleWKT.WKTRecursive<DataSchemaDetails.CustomizedStructConfig>.self,
      forKey: .customizedStructConfig)
    self.granularity = try container.decodeIfPresent(
      DataSchemaDetails.Granularity.self, forKey: .granularity)
    self.searchStrategy = try container.decodeIfPresent(
      DataSchemaDetails.SearchStrategy.self, forKey: .searchStrategy)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.type, forKey: .type)
    try container.encodeIfPresent(self.protoAnyConfig, forKey: .protoAnyConfig)
    try container.encodeIfPresent(self.listConfig, forKey: .listConfig)
    try container.encodeIfPresent(self.customizedStructConfig, forKey: .customizedStructConfig)
    try container.encodeIfPresent(self.granularity, forKey: .granularity)
    try container.encodeIfPresent(self.searchStrategy, forKey: .searchStrategy)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The configuration for `PROTO_ANY` data type.
  public struct ProtoAnyConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The type URI of the proto message.
    public var typeUri: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ProtoAnyConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ProtoAnyConfig().with { $0.typeUri = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let typeUri = CodingKeys(stringValue: "typeUri")

      static let _knownKeys: Set<Swift.String> = [
        "typeUri"
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .typeUri) {
        self.typeUri = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.typeUri, forKey: .typeUri)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.DataSchemaDetails.ProtoAnyConfig"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The configuration for `LIST` data type.
  public struct ListConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The value's data schema in the list.
    public var valueSchema: GoogleWKT.WKTRecursive<DataSchemaDetails>? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ListConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ListConfig().with { $0.valueSchema = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let valueSchema = CodingKeys(stringValue: "valueSchema")

      static let _knownKeys: Set<Swift.String> = [
        "valueSchema"
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.valueSchema = try container.decodeIfPresent(
        GoogleWKT.WKTRecursive<DataSchemaDetails>.self, forKey: .valueSchema)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.valueSchema, forKey: .valueSchema)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.DataSchemaDetails.ListConfig"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The configuration for `CUSTOMIZED_STRUCT` data type.
  public struct CustomizedStructConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Direct child elements data schemas.
    public var fieldSchemas: [Swift.String: DataSchemaDetails] = [:]

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `CustomizedStructConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CustomizedStructConfig().with { $0.fieldSchemas = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let fieldSchemas = CodingKeys(stringValue: "fieldSchemas")

      static let _knownKeys: Set<Swift.String> = [
        "fieldSchemas"
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        [Swift.String: DataSchemaDetails].self, forKey: .fieldSchemas)
      {
        self.fieldSchemas = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.fieldSchemas, forKey: .fieldSchemas)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.DataSchemaDetails.CustomizedStructConfig"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The search strategy for annotations value of the `key`.
  public struct SearchStrategy: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The type of search strategy to be applied on the `key` above.
    /// The allowed `search_strategy_type` is different for different data types,
    /// which is documented in the DataSchemaDetails.DataType. Specifying
    /// unsupported `search_strategy_type` for data types will result in
    /// INVALID_ARGUMENT error.
    public var searchStrategyType: DataSchemaDetails.SearchStrategy.SearchStrategyType? = nil

    /// Optional. Configs the path to the confidence score, and the threshold.
    /// Only if the score is greater than the threshold, current field will be
    /// built into the index. Only applies to leaf nodes using EXACT_SEARCH or
    /// SMART_SEARCH.
    public var confidenceScoreIndexConfig:
      DataSchemaDetails.SearchStrategy.ConfidenceScoreIndexConfig? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SearchStrategy`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SearchStrategy().with { $0.searchStrategyType = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let searchStrategyType = CodingKeys(stringValue: "searchStrategyType")
      static let confidenceScoreIndexConfig = CodingKeys(stringValue: "confidenceScoreIndexConfig")

      static let _knownKeys: Set<Swift.String> = [
        "searchStrategyType",
        "confidenceScoreIndexConfig",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.searchStrategyType = try container.decodeIfPresent(
        DataSchemaDetails.SearchStrategy.SearchStrategyType.self, forKey: .searchStrategyType)
      self.confidenceScoreIndexConfig = try container.decodeIfPresent(
        DataSchemaDetails.SearchStrategy.ConfidenceScoreIndexConfig.self,
        forKey: .confidenceScoreIndexConfig)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.searchStrategyType, forKey: .searchStrategyType)
      try container.encodeIfPresent(
        self.confidenceScoreIndexConfig, forKey: .confidenceScoreIndexConfig)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Filter on the confidence score. Only adds to index if the confidence
    /// score is higher than the threshold.
    /// Example data schema:
    /// key: "name-confidence-pair"
    /// type: CUSTOMIZED_STRUCT
    /// granularity: GRANULARITY_PARTITION_LEVEL
    /// customized_struct_config {
    ///   field_schemas {
    ///     key: "name"
    ///     type: STRING
    ///     granularity: GRANULARITY_PARTITION_LEVEL
    ///     search_strategy {
    ///       search_strategy_type: SMART_SEARCH
    ///       confidence_score_index_config {
    ///         field_path: "name-confidence-pair.score"
    ///         threshold: 0.6
    ///       }
    ///     }
    ///   }
    ///   field_schemas {
    ///     key: "score"
    ///     type: FLOAT
    ///     granularity: GRANULARITY_PARTITION_LEVEL
    ///   }
    /// }
    /// This means only "name" with score > 0.6 will be indexed.
    public struct ConfidenceScoreIndexConfig: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Required. The path to the confidence score field. It is a string that
      /// concatenates all the data schema keys along the path. See the example
      /// above. If the data schema contains LIST, use '_ENTRIES' to concatenate.
      /// Example data schema contains a list:
      /// "key": "list-name-score",
      /// "schemaDetails": {
      ///   "type": "LIST",
      ///   "granularity": "GRANULARITY_PARTITION_LEVEL",
      ///   "listConfig": {
      ///     "valueSchema": {
      ///       "type": "CUSTOMIZED_STRUCT",
      ///       "granularity": "GRANULARITY_PARTITION_LEVEL",
      ///       "customizedStructConfig": {
      ///         "fieldSchemas": {
      ///           "name": {
      ///             "type": "STRING",
      ///             "granularity": "GRANULARITY_PARTITION_LEVEL",
      ///             "searchStrategy": {
      ///               "searchStrategyType": "SMART_SEARCH"
      ///               "confidence_score_index_config": {
      ///                 "field_path": "list-name-score._ENTRIES.score",
      ///                 "threshold": "0.9",
      ///               }
      ///             }
      ///           },
      ///           "score": {
      ///             "type": "FLOAT",
      ///             "granularity": "GRANULARITY_PARTITION_LEVEL",
      ///           }
      ///         }
      ///       }
      ///     }
      ///   }
      /// }
      public var fieldPath: Swift.String = Swift.String()

      /// Required. The threshold.
      public var threshold: Swift.Float = Swift.Float()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `ConfidenceScoreIndexConfig`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = ConfidenceScoreIndexConfig().with { $0.fieldPath = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let fieldPath = CodingKeys(stringValue: "fieldPath")
        static let threshold = CodingKeys(stringValue: "threshold")

        static let _knownKeys: Set<Swift.String> = [
          "fieldPath",
          "threshold",
        ]
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .fieldPath) {
          self.fieldPath = value
        }
        if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .threshold) {
          self.threshold = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.fieldPath, forKey: .fieldPath)
        try container.encode(self.threshold, forKey: .threshold)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.visionai.v1.DataSchemaDetails.SearchStrategy.ConfidenceScoreIndexConfig"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// The types of search strategies to be applied on the annotation key.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum SearchStrategyType: Codable, Equatable, Hashable, Sendable {
      /// Annotatation values of the `key` above will not be searchable.
      case noSearch
      /// When searching with `key`, the value must be exactly as the annotation
      /// value that has been ingested.
      case exactSearch
      /// When searching with `key`, Warehouse will perform broad search based on
      /// semantic of the annotation value.
      case smartSearch
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .noSearch
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .noSearch: return 0
        case .exactSearch: return 1
        case .smartSearch: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .noSearch: return "NO_SEARCH"
        case .exactSearch: return "EXACT_SEARCH"
        case .smartSearch: return "SMART_SEARCH"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SearchStrategyType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "NO_SEARCH": self = .noSearch
        case "EXACT_SEARCH": self = .exactSearch
        case "SMART_SEARCH": self = .smartSearch
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SearchStrategyType/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .noSearch
        case 1: self = .exactSearch
        case 2: self = .smartSearch
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .noSearch: return try container.encode("NO_SEARCH")
        case .exactSearch: return try container.encode("EXACT_SEARCH")
        case .smartSearch: return try container.encode("SMART_SEARCH")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.DataSchemaDetails.SearchStrategy"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Data type of the annotation.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum DataType: Codable, Equatable, Hashable, Sendable {
    /// Unspecified type.
    case unspecified
    /// Integer type.
    /// Allowed search strategies:
    /// - DataSchema.SearchStrategy.NO_SEARCH,
    /// - DataSchema.SearchStrategy.EXACT_SEARCH.
    ///   Supports query by IntRangeArray.
    case integer
    /// Float type.
    /// Allowed search strategies:
    /// - DataSchema.SearchStrategy.NO_SEARCH,
    /// - DataSchema.SearchStrategy.EXACT_SEARCH.
    ///   Supports query by FloatRangeArray.
    case float
    /// String type.
    /// Allowed search strategies:
    /// - DataSchema.SearchStrategy.NO_SEARCH,
    /// - DataSchema.SearchStrategy.EXACT_SEARCH,
    /// - DataSchema.SearchStrategy.SMART_SEARCH.
    case string
    /// Supported formats:
    /// %Y-%m-%dT%H:%M:%E*S%E*z (absl::RFC3339_full)
    /// %Y-%m-%dT%H:%M:%E*S
    /// %Y-%m-%dT%H:%M%E*z
    /// %Y-%m-%dT%H:%M
    /// %Y-%m-%dT%H%E*z
    /// %Y-%m-%dT%H
    /// %Y-%m-%d%E*z
    /// %Y-%m-%d
    /// %Y-%m
    /// %Y
    /// Allowed search strategies:
    /// - DataSchema.SearchStrategy.NO_SEARCH,
    /// - DataSchema.SearchStrategy.EXACT_SEARCH.
    ///   Supports query by DateTimeRangeArray.
    case datetime
    /// Struct type.
    /// - SearchStrategy:
    ///   * Data Schema that's CUSTOMIZED_STRUCT cannot set search strategy.
    ///   * Leaf-node elements allow setting search strategy based on element's
    ///     SearchStrategy restriction.
    /// - Nested layer restrictions:
    ///   * Data Schema that's CUSTOMIZED_STRUCT allows its fields to be of
    ///     CUSTOMIZED_STRUCT as well, but the overall layers restriction is 10.
    case customizedStruct
    /// Geo coordinate type.
    /// Allowed search strategies:
    /// - DataSchema.SearchStrategy.NO_SEARCH,
    /// - DataSchema.SearchStrategy.EXACT_SEARCH.
    ///   Supports query by GeoLocationArray.
    case geoCoordinate
    /// Type to pass any proto as available in annotations.proto. Only use
    /// internally.
    /// Available proto types and its corresponding search behavior:
    /// - ImageObjectDetectionPredictionResult, allows SMART_SEARCH on
    ///   display_names and NO_SEARCH.
    /// - ClassificationPredictionResult, allows SMART_SEARCH on display_names
    ///   and NO_SEARCH.
    /// - ImageSegmentationPredictionResult, allows NO_SEARCH.
    /// - VideoActionRecognitionPredictionResult, allows SMART_SEARCH on
    ///   display_name and NO_SEARCH.
    /// - VideoObjectTrackingPredictionResult, allows SMART_SEARCH on
    ///   display_name and NO_SEARCH.
    /// - VideoClassificationPredictionResult, allows SMART_SEARCH on
    ///   display_name and NO_SEARCH.
    /// - OccupancyCountingPredictionResult, allows EXACT_SEARCH on
    ///   stats.full_frame_count.count and NO_SEARCH.
    /// - ObjectDetectionPredictionResult, allows SMART_SEARCH on
    ///   identified_boxes.entity.label_string and NO_SEARCH.
    case protoAny
    /// Boolean type.
    /// Allowed search strategies:
    /// - DataSchema.SearchStrategy.NO_SEARCH,
    /// - DataSchema.SearchStrategy.EXACT_SEARCH.
    case boolean
    /// List type.
    ///  - Each element in the list must be of the exact same data schema;
    ///    otherwise, they are invalid arguments.
    ///  - List level cannot set search strategy. Leaf node level can do.
    ///  - Elements cannot be another list (no list of list).
    ///  - Elements can be CUSTOMIZED_STRUCT, and max number of layers is 10.
    case list
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .integer: return 1
      case .float: return 2
      case .string: return 3
      case .datetime: return 5
      case .customizedStruct: return 6
      case .geoCoordinate: return 7
      case .protoAny: return 8
      case .boolean: return 9
      case .list: return 10
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DATA_TYPE_UNSPECIFIED"
      case .integer: return "INTEGER"
      case .float: return "FLOAT"
      case .string: return "STRING"
      case .datetime: return "DATETIME"
      case .customizedStruct: return "CUSTOMIZED_STRUCT"
      case .geoCoordinate: return "GEO_COORDINATE"
      case .protoAny: return "PROTO_ANY"
      case .boolean: return "BOOLEAN"
      case .list: return "LIST"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DataType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DATA_TYPE_UNSPECIFIED": self = .unspecified
      case "INTEGER": self = .integer
      case "FLOAT": self = .float
      case "STRING": self = .string
      case "DATETIME": self = .datetime
      case "GEO_COORDINATE": self = .geoCoordinate
      case "PROTO_ANY": self = .protoAny
      case "BOOLEAN": self = .boolean
      case "LIST": self = .list
      case "CUSTOMIZED_STRUCT": self = .customizedStruct
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DataType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .integer
      case 2: self = .float
      case 3: self = .string
      case 5: self = .datetime
      case 6: self = .customizedStruct
      case 7: self = .geoCoordinate
      case 8: self = .protoAny
      case 9: self = .boolean
      case 10: self = .list
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("DATA_TYPE_UNSPECIFIED")
      case .integer: return try container.encode("INTEGER")
      case .float: return try container.encode("FLOAT")
      case .string: return try container.encode("STRING")
      case .datetime: return try container.encode("DATETIME")
      case .customizedStruct: return try container.encode("CUSTOMIZED_STRUCT")
      case .geoCoordinate: return try container.encode("GEO_COORDINATE")
      case .protoAny: return try container.encode("PROTO_ANY")
      case .boolean: return try container.encode("BOOLEAN")
      case .list: return try container.encode("LIST")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The granularity of annotations under this DataSchema.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Granularity: Codable, Equatable, Hashable, Sendable {
    /// Unspecified granularity.
    case unspecified
    /// Asset-level granularity (annotations must not contain partition info).
    case assetLevel
    /// Partition-level granularity (annotations must contain partition info).
    case partitionLevel
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .assetLevel: return 1
      case .partitionLevel: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "GRANULARITY_UNSPECIFIED"
      case .assetLevel: return "GRANULARITY_ASSET_LEVEL"
      case .partitionLevel: return "GRANULARITY_PARTITION_LEVEL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Granularity/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "GRANULARITY_UNSPECIFIED": self = .unspecified
      case "GRANULARITY_ASSET_LEVEL": self = .assetLevel
      case "GRANULARITY_PARTITION_LEVEL": self = .partitionLevel
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Granularity/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .assetLevel
      case 2: self = .partitionLevel
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("GRANULARITY_UNSPECIFIED")
      case .assetLevel: return try container.encode("GRANULARITY_ASSET_LEVEL")
      case .partitionLevel: return try container.encode("GRANULARITY_PARTITION_LEVEL")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.DataSchemaDetails"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
