// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A description of resources that are dedicated to a DeployedModel, and
/// that need a higher degree of manual configuration.
public struct DedicatedResources: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Immutable. The specification of a single machine used by the
  /// prediction.
  public var machineSpec: MachineSpec? = nil

  /// Required. Immutable. The minimum number of machine replicas this
  /// DeployedModel will be always deployed on. This value must be greater than
  /// or equal to 1.
  ///
  /// If traffic against the DeployedModel increases, it may dynamically be
  /// deployed onto more replicas, and as traffic decreases, some of these extra
  /// replicas may be freed.
  public var minReplicaCount: Swift.Int32 = Swift.Int32()

  /// Immutable. The maximum number of replicas this DeployedModel may be
  /// deployed on when the traffic against it increases. If the requested value
  /// is too large, the deployment will error, but if deployment succeeds then
  /// the ability to scale the model to that many replicas is guaranteed (barring
  /// service outages). If traffic against the DeployedModel increases beyond
  /// what its replicas at maximum may handle, a portion of the traffic will be
  /// dropped. If this value is not provided, will use
  /// [min_replica_count][google.cloud.visionai.v1.DedicatedResources.min_replica_count]
  /// as the default value.
  ///
  /// The value of this field impacts the charge against Vertex CPU and GPU
  /// quotas. Specifically, you will be charged for max_replica_count *
  /// number of cores in the selected machine type) and (max_replica_count *
  /// number of GPUs per replica in the selected machine type).
  ///
  /// [google.cloud.visionai.v1.DedicatedResources.min_replica_count]: <doc:DedicatedResources/minReplicaCount>
  public var maxReplicaCount: Swift.Int32 = Swift.Int32()

  /// Immutable. The metric specifications that overrides a resource
  /// utilization metric (CPU utilization, accelerator's duty cycle, and so on)
  /// target value (default to 60 if not set). At most one entry is allowed per
  /// metric.
  ///
  /// If
  /// [machine_spec.accelerator_count][google.cloud.visionai.v1.MachineSpec.accelerator_count]
  /// is above 0, the autoscaling will be based on both CPU utilization and
  /// accelerator's duty cycle metrics and scale up when either metrics exceeds
  /// its target value while scale down if both metrics are under their target
  /// value. The default target value is 60 for both metrics.
  ///
  /// If
  /// [machine_spec.accelerator_count][google.cloud.visionai.v1.MachineSpec.accelerator_count]
  /// is 0, the autoscaling will be based on CPU utilization metric only with
  /// default target value 60 if not explicitly set.
  ///
  /// For example, in the case of Online Prediction, if you want to override
  /// target CPU utilization to 80, you should set
  /// [autoscaling_metric_specs.metric_name][google.cloud.visionai.v1.AutoscalingMetricSpec.metric_name]
  /// to `aiplatform.googleapis.com/prediction/online/cpu/utilization` and
  /// [autoscaling_metric_specs.target][google.cloud.visionai.v1.AutoscalingMetricSpec.target]
  /// to `80`.
  ///
  /// [google.cloud.visionai.v1.AutoscalingMetricSpec.metric_name]: <doc:AutoscalingMetricSpec/metricName>
  /// [google.cloud.visionai.v1.AutoscalingMetricSpec.target]: <doc:AutoscalingMetricSpec/target>
  /// [google.cloud.visionai.v1.MachineSpec.accelerator_count]: <doc:MachineSpec/acceleratorCount>
  public var autoscalingMetricSpecs: [AutoscalingMetricSpec] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DedicatedResources`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DedicatedResources().with { $0.machineSpec = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let machineSpec = CodingKeys(stringValue: "machineSpec")
    static let minReplicaCount = CodingKeys(stringValue: "minReplicaCount")
    static let maxReplicaCount = CodingKeys(stringValue: "maxReplicaCount")
    static let autoscalingMetricSpecs = CodingKeys(stringValue: "autoscalingMetricSpecs")

    static let _knownKeys: Set<Swift.String> = [
      "machineSpec",
      "minReplicaCount",
      "maxReplicaCount",
      "autoscalingMetricSpecs",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.machineSpec = try container.decodeIfPresent(MachineSpec.self, forKey: .machineSpec)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .minReplicaCount) {
      self.minReplicaCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxReplicaCount) {
      self.maxReplicaCount = value
    }
    if let value = try container.decodeIfPresent(
      [AutoscalingMetricSpec].self, forKey: .autoscalingMetricSpecs)
    {
      self.autoscalingMetricSpecs = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.machineSpec, forKey: .machineSpec)
    try container.encode(self.minReplicaCount, forKey: .minReplicaCount)
    try container.encode(self.maxReplicaCount, forKey: .maxReplicaCount)
    try container.encode(self.autoscalingMetricSpecs, forKey: .autoscalingMetricSpecs)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `DedicatedResources`: `"type.googleapis.com/google.cloud.visionai.v1.DedicatedResources"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.DedicatedResources"
  }

  /// Initialize an instance of `DedicatedResources` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.visionai.v1.DedicatedResources"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `DedicatedResources` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
