// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Prediction output format for Image Segmentation.
public struct ImageSegmentationPredictionResult: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// A PNG image where each pixel in the mask represents the category in which
  /// the pixel in the original image was predicted to belong to. The size of
  /// this image will be the same as the original image. The mapping between the
  /// AnntoationSpec and the color can be found in model's metadata. The model
  /// will choose the most likely category and if none of the categories reach
  /// the confidence threshold, the pixel will be marked as background.
  public var categoryMask: Swift.String = Swift.String()

  /// A one channel image which is encoded as an 8bit lossless PNG. The size of
  /// the image will be the same as the original image. For a specific pixel,
  /// darker color means less confidence in correctness of the cateogry in the
  /// categoryMask for the corresponding pixel. Black means no confidence and
  /// white means complete confidence.
  public var confidenceMask: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ImageSegmentationPredictionResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ImageSegmentationPredictionResult().with { $0.categoryMask = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let categoryMask = CodingKeys(stringValue: "categoryMask")
    static let confidenceMask = CodingKeys(stringValue: "confidenceMask")

    static let _knownKeys: Set<Swift.String> = [
      "categoryMask",
      "confidenceMask",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .categoryMask) {
      self.categoryMask = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .confidenceMask) {
      self.confidenceMask = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.categoryMask, forKey: .categoryMask)
    try container.encode(self.confidenceMask, forKey: .confidenceMask)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `ImageSegmentationPredictionResult`: `"type.googleapis.com/google.cloud.visionai.v1.ImageSegmentationPredictionResult"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.ImageSegmentationPredictionResult"
  }

  /// Initialize an instance of `ImageSegmentationPredictionResult` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.visionai.v1.ImageSegmentationPredictionResult"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `ImageSegmentationPredictionResult` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
