// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Message describing Instance object
/// Next ID: 12
public struct Instance: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. name of resource
  public var name: Swift.String = Swift.String()

  /// Output only. [Output only] Create timestamp
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. [Output only] Update timestamp
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Labels as key value pairs
  public var labels: [Swift.String: Swift.String] = [:]

  /// Required. A user friendly display name for the solution.
  public var displayName: Swift.String = Swift.String()

  /// A description for this instance.
  public var description: Swift.String = Swift.String()

  /// The instance type for the current instance.
  public var instanceType: Instance.InstanceType = Instance.InstanceType()

  /// The input resources for the current application instance.
  /// For example:
  /// input_resources:
  /// visionai.googleapis.com/v1/projects/123/locations/us-central1/clusters/456/streams/stream-a
  public var inputResources: [Instance.InputResource] = []

  /// All the output resources associated to one application instance.
  public var outputResources: [Instance.OutputResource] = []

  /// State of the instance.
  public var state: Instance.State = Instance.State()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Instance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Instance().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let description = CodingKeys(stringValue: "description")
    static let instanceType = CodingKeys(stringValue: "instanceType")
    static let inputResources = CodingKeys(stringValue: "inputResources")
    static let outputResources = CodingKeys(stringValue: "outputResources")
    static let state = CodingKeys(stringValue: "state")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "labels",
      "displayName",
      "description",
      "instanceType",
      "inputResources",
      "outputResources",
      "state",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Instance.InstanceType.self, forKey: .instanceType)
    {
      self.instanceType = value
    }
    if let value = try container.decodeIfPresent(
      [Instance.InputResource].self, forKey: .inputResources)
    {
      self.inputResources = value
    }
    if let value = try container.decodeIfPresent(
      [Instance.OutputResource].self, forKey: .outputResources)
    {
      self.outputResources = value
    }
    if let value = try container.decodeIfPresent(Instance.State.self, forKey: .state) {
      self.state = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.instanceType, forKey: .instanceType)
    try container.encode(self.inputResources, forKey: .inputResources)
    try container.encode(self.outputResources, forKey: .outputResources)
    try container.encode(self.state, forKey: .state)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Message of input resource used in one application instance.
  public struct InputResource: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Data type for the current input resource.
    public var dataType: GoogleCloudVideoAIV1.DataType = GoogleCloudVideoAIV1.DataType()

    /// The name of graph node who receives the input resource.
    /// For example:
    /// input_resource:
    /// visionai.googleapis.com/v1/projects/123/locations/us-central1/clusters/456/streams/input-stream-a
    /// consumer_node: stream-input
    public var consumerNode: Swift.String = Swift.String()

    /// The specific input resource binding which will consume the current Input
    /// Resource, can be ignored is there is only 1 input binding.
    public var inputResourceBinding: Swift.String = Swift.String()

    /// Contains resource annotations.
    public var annotations: ResourceAnnotations? = nil

    /// Required. Specify the input to the application instance.
    public var inputResourceInformation: InputResourceInformationOneOf? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `InputResource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = InputResource().with { $0.inputResource = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let inputResource = CodingKeys(stringValue: "inputResource")
      static let annotatedStream = CodingKeys(stringValue: "annotatedStream")
      static let dataType = CodingKeys(stringValue: "dataType")
      static let consumerNode = CodingKeys(stringValue: "consumerNode")
      static let inputResourceBinding = CodingKeys(stringValue: "inputResourceBinding")
      static let annotations = CodingKeys(stringValue: "annotations")

      static let _knownKeys: Set<Swift.String> = [
        "inputResource",
        "annotatedStream",
        "dataType",
        "consumerNode",
        "inputResourceBinding",
        "annotations",
      ]
    }

    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        GoogleCloudVideoAIV1.DataType.self, forKey: .dataType)
      {
        self.dataType = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .consumerNode) {
        self.consumerNode = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .inputResourceBinding)
      {
        self.inputResourceBinding = value
      }
      self.annotations = try container.decodeIfPresent(
        ResourceAnnotations.self, forKey: .annotations)

      var inputResourceInformation: InputResourceInformationOneOf? = nil
      let inputResourceInformationCheckAndSet = {
        if inputResourceInformation != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'inputResourceInformation'"))
        }
        inputResourceInformation = $0
      }
      if let inputResource = try container.decodeIfPresent(
        Swift.String.self, forKey: .inputResource)
      {
        try inputResourceInformationCheckAndSet(.inputResource(inputResource))
      }
      if let annotatedStream = try container.decodeIfPresent(
        StreamWithAnnotation.self, forKey: .annotatedStream)
      {
        try inputResourceInformationCheckAndSet(.annotatedStream(annotatedStream))
      }
      self.inputResourceInformation = inputResourceInformation
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.dataType, forKey: .dataType)
      try container.encode(self.consumerNode, forKey: .consumerNode)
      try container.encode(self.inputResourceBinding, forKey: .inputResourceBinding)
      try container.encodeIfPresent(self.annotations, forKey: .annotations)

      if let choice = self.inputResourceInformation {
        switch choice {
        case .inputResource(let value):
          try container.encode(value, forKey: .inputResource)
        case .annotatedStream(let value):
          try container.encode(value, forKey: .annotatedStream)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Required. Specify the input to the application instance.
    public enum InputResourceInformationOneOf: Codable, Equatable, Sendable {
      /// The direct input resource name.
      /// If the instance type is STREAMING_PREDICTION, the input resource is in
      /// format of
      /// "projects/123/locations/us-central1/clusters/456/streams/stream-a".
      /// If the instance type is BATCH_PREDICTION from Cloud Storage input
      /// container, the input resource is in format of "gs://bucket-a".
      case inputResource(Swift.String)
      /// If the input resource is VisionAI Stream, the associated annotations
      /// can be specified using annotated_stream instead.
      @available(*, deprecated)
      indirect case annotatedStream(StreamWithAnnotation)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.Instance.InputResource"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Message of output resource used in one application instance.
  public struct OutputResource: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The output resource name for the current application instance.
    public var outputResource: Swift.String = Swift.String()

    /// The name of graph node who produces the output resource name.
    /// For example:
    /// output_resource:
    /// /projects/123/locations/us-central1/clusters/456/streams/output-application-789-stream-a-occupancy-counting
    /// producer_node: occupancy-counting
    public var producerNode: Swift.String = Swift.String()

    /// The specific output resource binding which produces the current
    /// OutputResource.
    public var outputResourceBinding: Swift.String = Swift.String()

    /// Output only. Whether the output resource is temporary which means the
    /// resource is generated during the deployment of the application. Temporary
    /// resource will be deleted during the undeployment of the application.
    public var isTemporary: Swift.Bool = Swift.Bool()

    /// Output only. Whether the output resource is created automatically by the
    /// Vision AI App Platform.
    public var autogen: Swift.Bool = Swift.Bool()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `OutputResource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = OutputResource().with { $0.outputResource = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let outputResource = CodingKeys(stringValue: "outputResource")
      static let producerNode = CodingKeys(stringValue: "producerNode")
      static let outputResourceBinding = CodingKeys(stringValue: "outputResourceBinding")
      static let isTemporary = CodingKeys(stringValue: "isTemporary")
      static let autogen = CodingKeys(stringValue: "autogen")

      static let _knownKeys: Set<Swift.String> = [
        "outputResource",
        "producerNode",
        "outputResourceBinding",
        "isTemporary",
        "autogen",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .outputResource) {
        self.outputResource = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .producerNode) {
        self.producerNode = value
      }
      if let value = try container.decodeIfPresent(
        Swift.String.self, forKey: .outputResourceBinding)
      {
        self.outputResourceBinding = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .isTemporary) {
        self.isTemporary = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .autogen) {
        self.autogen = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.outputResource, forKey: .outputResource)
      try container.encode(self.producerNode, forKey: .producerNode)
      try container.encode(self.outputResourceBinding, forKey: .outputResourceBinding)
      try container.encode(self.isTemporary, forKey: .isTemporary)
      try container.encode(self.autogen, forKey: .autogen)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.Instance.OutputResource"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// All the supported instance types.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum InstanceType: Codable, Equatable, Hashable, Sendable {
    /// Unspecified instance type.
    /// If the instance type is not specified, the default one is
    /// STREAMING_PREDICTION.
    case unspecified
    /// Instance type for streaming prediction.
    case streamingPrediction
    /// Instance type for batch prediction.
    case batchPrediction
    /// Instance type for online prediction.
    case onlinePrediction
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .streamingPrediction: return 1
      case .batchPrediction: return 2
      case .onlinePrediction: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "INSTANCE_TYPE_UNSPECIFIED"
      case .streamingPrediction: return "STREAMING_PREDICTION"
      case .batchPrediction: return "BATCH_PREDICTION"
      case .onlinePrediction: return "ONLINE_PREDICTION"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:InstanceType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "INSTANCE_TYPE_UNSPECIFIED": self = .unspecified
      case "STREAMING_PREDICTION": self = .streamingPrediction
      case "BATCH_PREDICTION": self = .batchPrediction
      case "ONLINE_PREDICTION": self = .onlinePrediction
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:InstanceType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .streamingPrediction
      case 2: self = .batchPrediction
      case 3: self = .onlinePrediction
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("INSTANCE_TYPE_UNSPECIFIED")
      case .streamingPrediction: return try container.encode("STREAMING_PREDICTION")
      case .batchPrediction: return try container.encode("BATCH_PREDICTION")
      case .onlinePrediction: return try container.encode("ONLINE_PREDICTION")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// State of the Instance
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Hashable, Sendable {
    /// The default value. This value is used if the state is omitted.
    case unspecified
    /// State CREATING.
    case creating
    /// State CREATED.
    case created
    /// State DEPLOYING.
    case deploying
    /// State DEPLOYED.
    case deployed
    /// State UNDEPLOYING.
    case undeploying
    /// State DELETED.
    case deleted
    /// State ERROR.
    case error
    /// State Updating
    case updating
    /// State Deleting.
    case deleting
    /// State Fixing.
    case fixing
    /// State Finished.
    case finished
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .created: return 2
      case .deploying: return 3
      case .deployed: return 4
      case .undeploying: return 5
      case .deleted: return 6
      case .error: return 7
      case .updating: return 8
      case .deleting: return 9
      case .fixing: return 10
      case .finished: return 11
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .created: return "CREATED"
      case .deploying: return "DEPLOYING"
      case .deployed: return "DEPLOYED"
      case .undeploying: return "UNDEPLOYING"
      case .deleted: return "DELETED"
      case .error: return "ERROR"
      case .updating: return "UPDATING"
      case .deleting: return "DELETING"
      case .fixing: return "FIXING"
      case .finished: return "FINISHED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "CREATED": self = .created
      case "DEPLOYING": self = .deploying
      case "DEPLOYED": self = .deployed
      case "UNDEPLOYING": self = .undeploying
      case "DELETED": self = .deleted
      case "ERROR": self = .error
      case "UPDATING": self = .updating
      case "DELETING": self = .deleting
      case "FIXING": self = .fixing
      case "FINISHED": self = .finished
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .created
      case 3: self = .deploying
      case 4: self = .deployed
      case 5: self = .undeploying
      case 6: self = .deleted
      case 7: self = .error
      case 8: self = .updating
      case 9: self = .deleting
      case 10: self = .fixing
      case 11: self = .finished
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .creating: return try container.encode("CREATING")
      case .created: return try container.encode("CREATED")
      case .deploying: return try container.encode("DEPLOYING")
      case .deployed: return try container.encode("DEPLOYED")
      case .undeploying: return try container.encode("UNDEPLOYING")
      case .deleted: return try container.encode("DELETED")
      case .error: return try container.encode("ERROR")
      case .updating: return try container.encode("UPDATING")
      case .deleting: return try container.encode("DELETING")
      case .fixing: return try container.encode("FIXING")
      case .finished: return try container.encode("FINISHED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.Instance"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
