// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Message describing OccupancyCountConfig.
public struct OccupancyCountConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Whether to count the appearances of people, output counts have 'people' as
  /// the key.
  public var enablePeopleCounting: Swift.Bool = Swift.Bool()

  /// Whether to count the appearances of vehicles, output counts will have
  /// 'vehicle' as the key.
  public var enableVehicleCounting: Swift.Bool = Swift.Bool()

  /// Whether to track each invidual object's loitering time inside the scene or
  /// specific zone.
  public var enableDwellingTimeTracking: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `OccupancyCountConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OccupancyCountConfig().with { $0.enablePeopleCounting = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let enablePeopleCounting = CodingKeys(stringValue: "enablePeopleCounting")
    static let enableVehicleCounting = CodingKeys(stringValue: "enableVehicleCounting")
    static let enableDwellingTimeTracking = CodingKeys(stringValue: "enableDwellingTimeTracking")

    static let _knownKeys: Set<Swift.String> = [
      "enablePeopleCounting",
      "enableVehicleCounting",
      "enableDwellingTimeTracking",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enablePeopleCounting) {
      self.enablePeopleCounting = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enableVehicleCounting) {
      self.enableVehicleCounting = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .enableDwellingTimeTracking)
    {
      self.enableDwellingTimeTracking = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.enablePeopleCounting, forKey: .enablePeopleCounting)
    try container.encode(self.enableVehicleCounting, forKey: .enableVehicleCounting)
    try container.encode(self.enableDwellingTimeTracking, forKey: .enableDwellingTimeTracking)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.OccupancyCountConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
