// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The prediction result proto for occupancy counting.
public struct OccupancyCountingPredictionResult: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Current timestamp.
  public var currentTime: GoogleWKT.WKTTimestamp? = nil

  /// A list of identified boxes.
  public var identifiedBoxes: [OccupancyCountingPredictionResult.IdentifiedBox] = []

  /// Detection statistics.
  public var stats: OccupancyCountingPredictionResult.Stats? = nil

  /// Track related information. All the tracks that are live at this timestamp.
  /// It only exists if tracking is enabled.
  public var trackInfo: [OccupancyCountingPredictionResult.TrackInfo] = []

  /// Dwell time related information. All the tracks that are live in a given
  /// zone with a start and end dwell time timestamp
  public var dwellTimeInfo: [OccupancyCountingPredictionResult.DwellTimeInfo] = []

  /// The presentation timestamp of the frame.
  public var pts: Swift.Int64? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `OccupancyCountingPredictionResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OccupancyCountingPredictionResult().with { $0.currentTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let currentTime = CodingKeys(stringValue: "currentTime")
    static let identifiedBoxes = CodingKeys(stringValue: "identifiedBoxes")
    static let stats = CodingKeys(stringValue: "stats")
    static let trackInfo = CodingKeys(stringValue: "trackInfo")
    static let dwellTimeInfo = CodingKeys(stringValue: "dwellTimeInfo")
    static let pts = CodingKeys(stringValue: "pts")

    static let _knownKeys: Set<Swift.String> = [
      "currentTime",
      "identifiedBoxes",
      "stats",
      "trackInfo",
      "dwellTimeInfo",
      "pts",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.currentTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .currentTime)
    if let value = try container.decodeIfPresent(
      [OccupancyCountingPredictionResult.IdentifiedBox].self, forKey: .identifiedBoxes)
    {
      self.identifiedBoxes = value
    }
    self.stats = try container.decodeIfPresent(
      OccupancyCountingPredictionResult.Stats.self, forKey: .stats)
    if let value = try container.decodeIfPresent(
      [OccupancyCountingPredictionResult.TrackInfo].self, forKey: .trackInfo)
    {
      self.trackInfo = value
    }
    if let value = try container.decodeIfPresent(
      [OccupancyCountingPredictionResult.DwellTimeInfo].self, forKey: .dwellTimeInfo)
    {
      self.dwellTimeInfo = value
    }
    self.pts = try container.decodeIfPresent(Swift.Int64.self, forKey: .pts)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.currentTime, forKey: .currentTime)
    try container.encode(self.identifiedBoxes, forKey: .identifiedBoxes)
    try container.encodeIfPresent(self.stats, forKey: .stats)
    try container.encode(self.trackInfo, forKey: .trackInfo)
    try container.encode(self.dwellTimeInfo, forKey: .dwellTimeInfo)
    try container.encodeIfPresent(self.pts, forKey: .pts)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The entity info for annotations from occupancy counting operator.
  public struct Entity: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Label id.
    public var labelId: Swift.Int64 = Swift.Int64()

    /// Human readable string of the label.
    public var labelString: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Entity`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Entity().with { $0.labelId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let labelId = CodingKeys(stringValue: "labelId")
      static let labelString = CodingKeys(stringValue: "labelString")

      static let _knownKeys: Set<Swift.String> = [
        "labelId",
        "labelString",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .labelId) {
        self.labelId = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .labelString) {
        self.labelString = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.labelId, forKey: .labelId)
      try container.encode(self.labelString, forKey: .labelString)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `Entity`: `"type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult.Entity"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult.Entity"
    }

    /// Initialize an instance of `Entity` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult.Entity"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `Entity` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Identified box contains location and the entity of the object.
  public struct IdentifiedBox: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// An unique id for this box.
    public var boxId: Swift.Int64 = Swift.Int64()

    /// Bounding Box in the normalized coordinates.
    public var normalizedBoundingBox:
      OccupancyCountingPredictionResult.IdentifiedBox.NormalizedBoundingBox? = nil

    /// Confidence score associated with this box.
    public var score: Swift.Float = Swift.Float()

    /// Entity of this box.
    public var entity: OccupancyCountingPredictionResult.Entity? = nil

    /// An unique id to identify a track. It should be consistent across frames.
    /// It only exists if tracking is enabled.
    public var trackId: Swift.Int64 = Swift.Int64()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `IdentifiedBox`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = IdentifiedBox().with { $0.boxId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let boxId = CodingKeys(stringValue: "boxId")
      static let normalizedBoundingBox = CodingKeys(stringValue: "normalizedBoundingBox")
      static let score = CodingKeys(stringValue: "score")
      static let entity = CodingKeys(stringValue: "entity")
      static let trackId = CodingKeys(stringValue: "trackId")

      static let _knownKeys: Set<Swift.String> = [
        "boxId",
        "normalizedBoundingBox",
        "score",
        "entity",
        "trackId",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .boxId) {
        self.boxId = value
      }
      self.normalizedBoundingBox = try container.decodeIfPresent(
        OccupancyCountingPredictionResult.IdentifiedBox.NormalizedBoundingBox.self,
        forKey: .normalizedBoundingBox)
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .score) {
        self.score = value
      }
      self.entity = try container.decodeIfPresent(
        OccupancyCountingPredictionResult.Entity.self, forKey: .entity)
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .trackId) {
        self.trackId = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.boxId, forKey: .boxId)
      try container.encodeIfPresent(self.normalizedBoundingBox, forKey: .normalizedBoundingBox)
      try container.encode(self.score, forKey: .score)
      try container.encodeIfPresent(self.entity, forKey: .entity)
      try container.encode(self.trackId, forKey: .trackId)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Bounding Box in the normalized coordinates.
    public struct NormalizedBoundingBox: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Min in x coordinate.
      public var xmin: Swift.Float = Swift.Float()

      /// Min in y coordinate.
      public var ymin: Swift.Float = Swift.Float()

      /// Width of the bounding box.
      public var width: Swift.Float = Swift.Float()

      /// Height of the bounding box.
      public var height: Swift.Float = Swift.Float()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `NormalizedBoundingBox`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = NormalizedBoundingBox().with { $0.xmin = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let xmin = CodingKeys(stringValue: "xmin")
        static let ymin = CodingKeys(stringValue: "ymin")
        static let width = CodingKeys(stringValue: "width")
        static let height = CodingKeys(stringValue: "height")

        static let _knownKeys: Set<Swift.String> = [
          "xmin",
          "ymin",
          "width",
          "height",
        ]
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .xmin) {
          self.xmin = value
        }
        if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .ymin) {
          self.ymin = value
        }
        if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .width) {
          self.width = value
        }
        if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .height) {
          self.height = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.xmin, forKey: .xmin)
        try container.encode(self.ymin, forKey: .ymin)
        try container.encode(self.width, forKey: .width)
        try container.encode(self.height, forKey: .height)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      /// The type URL for `NormalizedBoundingBox`: `"type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult.IdentifiedBox.NormalizedBoundingBox"`.
      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult.IdentifiedBox.NormalizedBoundingBox"
      }

      /// Initialize an instance of `NormalizedBoundingBox` by unpacking from a `GoogleWKT.WKTAny`.
      ///
      /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
      /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult.IdentifiedBox.NormalizedBoundingBox"`,
      ///   or if deserialization fails.
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }

      /// Packs this `NormalizedBoundingBox` into a `GoogleWKT.WKTStruct` representation.
      ///
      /// - Throws: An error if serialization fails.
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// The type URL for `IdentifiedBox`: `"type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult.IdentifiedBox"`.
    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult.IdentifiedBox"
    }

    /// Initialize an instance of `IdentifiedBox` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult.IdentifiedBox"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `IdentifiedBox` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The statistics info for annotations from occupancy counting operator.
  public struct Stats: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Counts of the full frame.
    public var fullFrameCount: [OccupancyCountingPredictionResult.Stats.ObjectCount] = []

    /// Crossing line counts.
    public var crossingLineCounts: [OccupancyCountingPredictionResult.Stats.CrossingLineCount] = []

    /// Active zone counts.
    public var activeZoneCounts: [OccupancyCountingPredictionResult.Stats.ActiveZoneCount] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Stats`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Stats().with { $0.fullFrameCount = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let fullFrameCount = CodingKeys(stringValue: "fullFrameCount")
      static let crossingLineCounts = CodingKeys(stringValue: "crossingLineCounts")
      static let activeZoneCounts = CodingKeys(stringValue: "activeZoneCounts")

      static let _knownKeys: Set<Swift.String> = [
        "fullFrameCount",
        "crossingLineCounts",
        "activeZoneCounts",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        [OccupancyCountingPredictionResult.Stats.ObjectCount].self, forKey: .fullFrameCount)
      {
        self.fullFrameCount = value
      }
      if let value = try container.decodeIfPresent(
        [OccupancyCountingPredictionResult.Stats.CrossingLineCount].self,
        forKey: .crossingLineCounts)
      {
        self.crossingLineCounts = value
      }
      if let value = try container.decodeIfPresent(
        [OccupancyCountingPredictionResult.Stats.ActiveZoneCount].self, forKey: .activeZoneCounts)
      {
        self.activeZoneCounts = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.fullFrameCount, forKey: .fullFrameCount)
      try container.encode(self.crossingLineCounts, forKey: .crossingLineCounts)
      try container.encode(self.activeZoneCounts, forKey: .activeZoneCounts)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The object info and instant count for annotations from occupancy counting
    /// operator.
    public struct ObjectCount: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Entity of this object.
      public var entity: OccupancyCountingPredictionResult.Entity? = nil

      /// Count of the object.
      public var count: Swift.Int32 = Swift.Int32()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `ObjectCount`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = ObjectCount().with { $0.entity = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let entity = CodingKeys(stringValue: "entity")
        static let count = CodingKeys(stringValue: "count")

        static let _knownKeys: Set<Swift.String> = [
          "entity",
          "count",
        ]
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.entity = try container.decodeIfPresent(
          OccupancyCountingPredictionResult.Entity.self, forKey: .entity)
        if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .count) {
          self.count = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.entity, forKey: .entity)
        try container.encode(self.count, forKey: .count)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      /// The type URL for `ObjectCount`: `"type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult.Stats.ObjectCount"`.
      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult.Stats.ObjectCount"
      }

      /// Initialize an instance of `ObjectCount` by unpacking from a `GoogleWKT.WKTAny`.
      ///
      /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
      /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult.Stats.ObjectCount"`,
      ///   or if deserialization fails.
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }

      /// Packs this `ObjectCount` into a `GoogleWKT.WKTStruct` representation.
      ///
      /// - Throws: An error if serialization fails.
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// The object info and accumulated count for annotations from occupancy
    /// counting operator.
    public struct AccumulatedObjectCount: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// The start time of the accumulated count.
      public var startTime: GoogleWKT.WKTTimestamp? = nil

      /// The object count for the accumulated count.
      public var objectCount: OccupancyCountingPredictionResult.Stats.ObjectCount? = nil

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `AccumulatedObjectCount`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = AccumulatedObjectCount().with { $0.startTime = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let startTime = CodingKeys(stringValue: "startTime")
        static let objectCount = CodingKeys(stringValue: "objectCount")

        static let _knownKeys: Set<Swift.String> = [
          "startTime",
          "objectCount",
        ]
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.startTime = try container.decodeIfPresent(
          GoogleWKT.WKTTimestamp.self, forKey: .startTime)
        self.objectCount = try container.decodeIfPresent(
          OccupancyCountingPredictionResult.Stats.ObjectCount.self, forKey: .objectCount)
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.startTime, forKey: .startTime)
        try container.encodeIfPresent(self.objectCount, forKey: .objectCount)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      /// The type URL for `AccumulatedObjectCount`: `"type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult.Stats.AccumulatedObjectCount"`.
      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult.Stats.AccumulatedObjectCount"
      }

      /// Initialize an instance of `AccumulatedObjectCount` by unpacking from a `GoogleWKT.WKTAny`.
      ///
      /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
      /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult.Stats.AccumulatedObjectCount"`,
      ///   or if deserialization fails.
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }

      /// Packs this `AccumulatedObjectCount` into a `GoogleWKT.WKTStruct` representation.
      ///
      /// - Throws: An error if serialization fails.
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// Message for Crossing line count.
    public struct CrossingLineCount: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Line annotation from the user.
      public var annotation: StreamAnnotation? = nil

      /// The direction that follows the right hand rule.
      public var positiveDirectionCounts: [OccupancyCountingPredictionResult.Stats.ObjectCount] = []

      /// The direction that is opposite to the right hand rule.
      public var negativeDirectionCounts: [OccupancyCountingPredictionResult.Stats.ObjectCount] = []

      /// The accumulated positive count.
      public var accumulatedPositiveDirectionCounts:
        [OccupancyCountingPredictionResult.Stats.AccumulatedObjectCount] = []

      /// The accumulated negative count.
      public var accumulatedNegativeDirectionCounts:
        [OccupancyCountingPredictionResult.Stats.AccumulatedObjectCount] = []

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `CrossingLineCount`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = CrossingLineCount().with { $0.annotation = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let annotation = CodingKeys(stringValue: "annotation")
        static let positiveDirectionCounts = CodingKeys(stringValue: "positiveDirectionCounts")
        static let negativeDirectionCounts = CodingKeys(stringValue: "negativeDirectionCounts")
        static let accumulatedPositiveDirectionCounts = CodingKeys(
          stringValue: "accumulatedPositiveDirectionCounts")
        static let accumulatedNegativeDirectionCounts = CodingKeys(
          stringValue: "accumulatedNegativeDirectionCounts")

        static let _knownKeys: Set<Swift.String> = [
          "annotation",
          "positiveDirectionCounts",
          "negativeDirectionCounts",
          "accumulatedPositiveDirectionCounts",
          "accumulatedNegativeDirectionCounts",
        ]
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.annotation = try container.decodeIfPresent(StreamAnnotation.self, forKey: .annotation)
        if let value = try container.decodeIfPresent(
          [OccupancyCountingPredictionResult.Stats.ObjectCount].self,
          forKey: .positiveDirectionCounts)
        {
          self.positiveDirectionCounts = value
        }
        if let value = try container.decodeIfPresent(
          [OccupancyCountingPredictionResult.Stats.ObjectCount].self,
          forKey: .negativeDirectionCounts)
        {
          self.negativeDirectionCounts = value
        }
        if let value = try container.decodeIfPresent(
          [OccupancyCountingPredictionResult.Stats.AccumulatedObjectCount].self,
          forKey: .accumulatedPositiveDirectionCounts)
        {
          self.accumulatedPositiveDirectionCounts = value
        }
        if let value = try container.decodeIfPresent(
          [OccupancyCountingPredictionResult.Stats.AccumulatedObjectCount].self,
          forKey: .accumulatedNegativeDirectionCounts)
        {
          self.accumulatedNegativeDirectionCounts = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.annotation, forKey: .annotation)
        try container.encode(self.positiveDirectionCounts, forKey: .positiveDirectionCounts)
        try container.encode(self.negativeDirectionCounts, forKey: .negativeDirectionCounts)
        try container.encode(
          self.accumulatedPositiveDirectionCounts, forKey: .accumulatedPositiveDirectionCounts)
        try container.encode(
          self.accumulatedNegativeDirectionCounts, forKey: .accumulatedNegativeDirectionCounts)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      /// The type URL for `CrossingLineCount`: `"type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult.Stats.CrossingLineCount"`.
      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult.Stats.CrossingLineCount"
      }

      /// Initialize an instance of `CrossingLineCount` by unpacking from a `GoogleWKT.WKTAny`.
      ///
      /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
      /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult.Stats.CrossingLineCount"`,
      ///   or if deserialization fails.
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }

      /// Packs this `CrossingLineCount` into a `GoogleWKT.WKTStruct` representation.
      ///
      /// - Throws: An error if serialization fails.
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// Message for the active zone count.
    public struct ActiveZoneCount: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Active zone annotation from the user.
      public var annotation: StreamAnnotation? = nil

      /// Counts in the zone.
      public var counts: [OccupancyCountingPredictionResult.Stats.ObjectCount] = []

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `ActiveZoneCount`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = ActiveZoneCount().with { $0.annotation = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let annotation = CodingKeys(stringValue: "annotation")
        static let counts = CodingKeys(stringValue: "counts")

        static let _knownKeys: Set<Swift.String> = [
          "annotation",
          "counts",
        ]
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.annotation = try container.decodeIfPresent(StreamAnnotation.self, forKey: .annotation)
        if let value = try container.decodeIfPresent(
          [OccupancyCountingPredictionResult.Stats.ObjectCount].self, forKey: .counts)
        {
          self.counts = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.annotation, forKey: .annotation)
        try container.encode(self.counts, forKey: .counts)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      /// The type URL for `ActiveZoneCount`: `"type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult.Stats.ActiveZoneCount"`.
      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult.Stats.ActiveZoneCount"
      }

      /// Initialize an instance of `ActiveZoneCount` by unpacking from a `GoogleWKT.WKTAny`.
      ///
      /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
      /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult.Stats.ActiveZoneCount"`,
      ///   or if deserialization fails.
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }

      /// Packs this `ActiveZoneCount` into a `GoogleWKT.WKTStruct` representation.
      ///
      /// - Throws: An error if serialization fails.
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// The type URL for `Stats`: `"type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult.Stats"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult.Stats"
    }

    /// Initialize an instance of `Stats` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult.Stats"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `Stats` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The track info for annotations from occupancy counting operator.
  public struct TrackInfo: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// An unique id to identify a track. It should be consistent across frames.
    public var trackId: Swift.String = Swift.String()

    /// Start timestamp of this track.
    public var startTime: GoogleWKT.WKTTimestamp? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `TrackInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TrackInfo().with { $0.trackId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let trackId = CodingKeys(stringValue: "trackId")
      static let startTime = CodingKeys(stringValue: "startTime")

      static let _knownKeys: Set<Swift.String> = [
        "trackId",
        "startTime",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .trackId) {
        self.trackId = value
      }
      self.startTime = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .startTime)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.trackId, forKey: .trackId)
      try container.encodeIfPresent(self.startTime, forKey: .startTime)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `TrackInfo`: `"type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult.TrackInfo"`.
    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult.TrackInfo"
    }

    /// Initialize an instance of `TrackInfo` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult.TrackInfo"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `TrackInfo` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The dwell time info for annotations from occupancy counting operator.
  public struct DwellTimeInfo: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// An unique id to identify a track. It should be consistent across frames.
    public var trackId: Swift.String = Swift.String()

    /// The unique id for the zone in which the object is dwelling/waiting.
    public var zoneId: Swift.String = Swift.String()

    /// The beginning time when a dwelling object has been identified in a zone.
    public var dwellStartTime: GoogleWKT.WKTTimestamp? = nil

    /// The end time when a dwelling object has exited in a zone.
    public var dwellEndTime: GoogleWKT.WKTTimestamp? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `DwellTimeInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DwellTimeInfo().with { $0.trackId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let trackId = CodingKeys(stringValue: "trackId")
      static let zoneId = CodingKeys(stringValue: "zoneId")
      static let dwellStartTime = CodingKeys(stringValue: "dwellStartTime")
      static let dwellEndTime = CodingKeys(stringValue: "dwellEndTime")

      static let _knownKeys: Set<Swift.String> = [
        "trackId",
        "zoneId",
        "dwellStartTime",
        "dwellEndTime",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .trackId) {
        self.trackId = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .zoneId) {
        self.zoneId = value
      }
      self.dwellStartTime = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .dwellStartTime)
      self.dwellEndTime = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .dwellEndTime)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.trackId, forKey: .trackId)
      try container.encode(self.zoneId, forKey: .zoneId)
      try container.encodeIfPresent(self.dwellStartTime, forKey: .dwellStartTime)
      try container.encodeIfPresent(self.dwellEndTime, forKey: .dwellEndTime)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `DwellTimeInfo`: `"type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult.DwellTimeInfo"`.
    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult.DwellTimeInfo"
    }

    /// Initialize an instance of `DwellTimeInfo` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult.DwellTimeInfo"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `DwellTimeInfo` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The type URL for `OccupancyCountingPredictionResult`: `"type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult"
  }

  /// Initialize an instance of `OccupancyCountingPredictionResult` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.visionai.v1.OccupancyCountingPredictionResult"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `OccupancyCountingPredictionResult` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
