// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Partition to specify the partition in time and space for sub-asset level
/// annotation.
public struct Partition: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Partition of asset in time.
  public var temporalPartition: Partition.TemporalPartition? = nil

  /// Partition of asset in space.
  public var spatialPartition: Partition.SpatialPartition? = nil

  /// Partition of asset in time.
  public var relativeTemporalPartition: Partition.RelativeTemporalPartition? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Partition`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Partition().with { $0.temporalPartition = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let temporalPartition = CodingKeys(stringValue: "temporalPartition")
    static let spatialPartition = CodingKeys(stringValue: "spatialPartition")
    static let relativeTemporalPartition = CodingKeys(stringValue: "relativeTemporalPartition")

    static let _knownKeys: Set<Swift.String> = [
      "temporalPartition",
      "spatialPartition",
      "relativeTemporalPartition",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.temporalPartition = try container.decodeIfPresent(
      Partition.TemporalPartition.self, forKey: .temporalPartition)
    self.spatialPartition = try container.decodeIfPresent(
      Partition.SpatialPartition.self, forKey: .spatialPartition)
    self.relativeTemporalPartition = try container.decodeIfPresent(
      Partition.RelativeTemporalPartition.self, forKey: .relativeTemporalPartition)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.temporalPartition, forKey: .temporalPartition)
    try container.encodeIfPresent(self.spatialPartition, forKey: .spatialPartition)
    try container.encodeIfPresent(
      self.relativeTemporalPartition, forKey: .relativeTemporalPartition)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Partition of asset in UTC Epoch time. Supported by STREAM_VIDEO corpus
  /// type.
  public struct TemporalPartition: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Start time of the partition.
    public var startTime: GoogleWKT.WKTTimestamp? = nil

    /// End time of the partition.
    public var endTime: GoogleWKT.WKTTimestamp? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `TemporalPartition`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TemporalPartition().with { $0.startTime = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let startTime = CodingKeys(stringValue: "startTime")
      static let endTime = CodingKeys(stringValue: "endTime")

      static let _knownKeys: Set<Swift.String> = [
        "startTime",
        "endTime",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.startTime = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .startTime)
      self.endTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .endTime)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.startTime, forKey: .startTime)
      try container.encodeIfPresent(self.endTime, forKey: .endTime)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.Partition.TemporalPartition"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Partition of asset in space.
  public struct SpatialPartition: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The minimum x coordinate value.
    public var xMin: Swift.Int64? = nil

    /// The minimum y coordinate value.
    public var yMin: Swift.Int64? = nil

    /// The maximum x coordinate value.
    public var xMax: Swift.Int64? = nil

    /// The maximum y coordinate value.
    public var yMax: Swift.Int64? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SpatialPartition`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SpatialPartition().with { $0.xMin = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let xMin = CodingKeys(stringValue: "xMin")
      static let yMin = CodingKeys(stringValue: "yMin")
      static let xMax = CodingKeys(stringValue: "xMax")
      static let yMax = CodingKeys(stringValue: "yMax")

      static let _knownKeys: Set<Swift.String> = [
        "xMin",
        "yMin",
        "xMax",
        "yMax",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.xMin = try container.decodeIfPresent(Swift.Int64.self, forKey: .xMin)
      self.yMin = try container.decodeIfPresent(Swift.Int64.self, forKey: .yMin)
      self.xMax = try container.decodeIfPresent(Swift.Int64.self, forKey: .xMax)
      self.yMax = try container.decodeIfPresent(Swift.Int64.self, forKey: .yMax)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.xMin, forKey: .xMin)
      try container.encodeIfPresent(self.yMin, forKey: .yMin)
      try container.encodeIfPresent(self.xMax, forKey: .xMax)
      try container.encodeIfPresent(self.yMax, forKey: .yMax)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.Partition.SpatialPartition"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Partition of asset in relative time. Supported by VIDEO_ON_DEMAND corpus
  /// type.
  public struct RelativeTemporalPartition: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Start time offset of the partition.
    public var startOffset: GoogleWKT.WKTDuration? = nil

    /// End time offset of the partition.
    public var endOffset: GoogleWKT.WKTDuration? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `RelativeTemporalPartition`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RelativeTemporalPartition().with { $0.startOffset = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let startOffset = CodingKeys(stringValue: "startOffset")
      static let endOffset = CodingKeys(stringValue: "endOffset")

      static let _knownKeys: Set<Swift.String> = [
        "startOffset",
        "endOffset",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.startOffset = try container.decodeIfPresent(
        GoogleWKT.WKTDuration.self, forKey: .startOffset)
      self.endOffset = try container.decodeIfPresent(GoogleWKT.WKTDuration.self, forKey: .endOffset)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.startOffset, forKey: .startOffset)
      try container.encodeIfPresent(self.endOffset, forKey: .endOffset)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.Partition.RelativeTemporalPartition"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.Partition"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
