// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Output format for Personal Protective Equipment Detection Operator.
public struct PersonalProtectiveEquipmentDetectionOutput: Codable, Equatable, GoogleWKT
    ._AnyPackable,
  Sendable
{
  /// Current timestamp.
  public var currentTime: GoogleWKT.WKTTimestamp? = nil

  /// A list of DetectedPersons.
  public var detectedPersons: [PersonalProtectiveEquipmentDetectionOutput.DetectedPerson] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PersonalProtectiveEquipmentDetectionOutput`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PersonalProtectiveEquipmentDetectionOutput().with { $0.currentTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let currentTime = CodingKeys(stringValue: "currentTime")
    static let detectedPersons = CodingKeys(stringValue: "detectedPersons")

    static let _knownKeys: Set<Swift.String> = [
      "currentTime",
      "detectedPersons",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.currentTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .currentTime)
    if let value = try container.decodeIfPresent(
      [PersonalProtectiveEquipmentDetectionOutput.DetectedPerson].self, forKey: .detectedPersons)
    {
      self.detectedPersons = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.currentTime, forKey: .currentTime)
    try container.encode(self.detectedPersons, forKey: .detectedPersons)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The entity info for annotations from person detection prediction result.
  public struct PersonEntity: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Entity id.
    public var personEntityId: Swift.Int64 = Swift.Int64()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PersonEntity`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PersonEntity().with { $0.personEntityId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let personEntityId = CodingKeys(stringValue: "personEntityId")

      static let _knownKeys: Set<Swift.String> = [
        "personEntityId"
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .personEntityId) {
        self.personEntityId = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.personEntityId, forKey: .personEntityId)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.visionai.v1.PersonalProtectiveEquipmentDetectionOutput.PersonEntity"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The entity info for annotations from PPE detection prediction result.
  public struct PPEEntity: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Label id.
    public var ppeLabelId: Swift.Int64 = Swift.Int64()

    /// Human readable string of the label (Examples: helmet, glove, mask).
    public var ppeLabelString: Swift.String = Swift.String()

    /// Human readable string of the super category label (Examples: head_cover,
    /// hands_cover, face_cover).
    public var ppeSupercategoryLabelString: Swift.String = Swift.String()

    /// Entity id.
    public var ppeEntityId: Swift.Int64 = Swift.Int64()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PPEEntity`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PPEEntity().with { $0.ppeLabelId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let ppeLabelId = CodingKeys(stringValue: "ppeLabelId")
      static let ppeLabelString = CodingKeys(stringValue: "ppeLabelString")
      static let ppeSupercategoryLabelString = CodingKeys(
        stringValue: "ppeSupercategoryLabelString")
      static let ppeEntityId = CodingKeys(stringValue: "ppeEntityId")

      static let _knownKeys: Set<Swift.String> = [
        "ppeLabelId",
        "ppeLabelString",
        "ppeSupercategoryLabelString",
        "ppeEntityId",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .ppeLabelId) {
        self.ppeLabelId = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ppeLabelString) {
        self.ppeLabelString = value
      }
      if let value = try container.decodeIfPresent(
        Swift.String.self, forKey: .ppeSupercategoryLabelString)
      {
        self.ppeSupercategoryLabelString = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .ppeEntityId) {
        self.ppeEntityId = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.ppeLabelId, forKey: .ppeLabelId)
      try container.encode(self.ppeLabelString, forKey: .ppeLabelString)
      try container.encode(self.ppeSupercategoryLabelString, forKey: .ppeSupercategoryLabelString)
      try container.encode(self.ppeEntityId, forKey: .ppeEntityId)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.visionai.v1.PersonalProtectiveEquipmentDetectionOutput.PPEEntity"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Bounding Box in the normalized coordinates.
  public struct NormalizedBoundingBox: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Min in x coordinate.
    public var xmin: Swift.Float = Swift.Float()

    /// Min in y coordinate.
    public var ymin: Swift.Float = Swift.Float()

    /// Width of the bounding box.
    public var width: Swift.Float = Swift.Float()

    /// Height of the bounding box.
    public var height: Swift.Float = Swift.Float()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `NormalizedBoundingBox`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = NormalizedBoundingBox().with { $0.xmin = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let xmin = CodingKeys(stringValue: "xmin")
      static let ymin = CodingKeys(stringValue: "ymin")
      static let width = CodingKeys(stringValue: "width")
      static let height = CodingKeys(stringValue: "height")

      static let _knownKeys: Set<Swift.String> = [
        "xmin",
        "ymin",
        "width",
        "height",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .xmin) {
        self.xmin = value
      }
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .ymin) {
        self.ymin = value
      }
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .width) {
        self.width = value
      }
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .height) {
        self.height = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.xmin, forKey: .xmin)
      try container.encode(self.ymin, forKey: .ymin)
      try container.encode(self.width, forKey: .width)
      try container.encode(self.height, forKey: .height)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.visionai.v1.PersonalProtectiveEquipmentDetectionOutput.NormalizedBoundingBox"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// PersonIdentified box contains the location and the entity info of the
  /// person.
  public struct PersonIdentifiedBox: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// An unique id for this box.
    public var boxId: Swift.Int64 = Swift.Int64()

    /// Bounding Box in the normalized coordinates.
    public var normalizedBoundingBox:
      PersonalProtectiveEquipmentDetectionOutput.NormalizedBoundingBox? = nil

    /// Confidence score associated with this box.
    public var confidenceScore: Swift.Float = Swift.Float()

    /// Person entity info.
    public var personEntity: PersonalProtectiveEquipmentDetectionOutput.PersonEntity? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PersonIdentifiedBox`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PersonIdentifiedBox().with { $0.boxId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let boxId = CodingKeys(stringValue: "boxId")
      static let normalizedBoundingBox = CodingKeys(stringValue: "normalizedBoundingBox")
      static let confidenceScore = CodingKeys(stringValue: "confidenceScore")
      static let personEntity = CodingKeys(stringValue: "personEntity")

      static let _knownKeys: Set<Swift.String> = [
        "boxId",
        "normalizedBoundingBox",
        "confidenceScore",
        "personEntity",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .boxId) {
        self.boxId = value
      }
      self.normalizedBoundingBox = try container.decodeIfPresent(
        PersonalProtectiveEquipmentDetectionOutput.NormalizedBoundingBox.self,
        forKey: .normalizedBoundingBox)
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .confidenceScore) {
        self.confidenceScore = value
      }
      self.personEntity = try container.decodeIfPresent(
        PersonalProtectiveEquipmentDetectionOutput.PersonEntity.self, forKey: .personEntity)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.boxId, forKey: .boxId)
      try container.encodeIfPresent(self.normalizedBoundingBox, forKey: .normalizedBoundingBox)
      try container.encode(self.confidenceScore, forKey: .confidenceScore)
      try container.encodeIfPresent(self.personEntity, forKey: .personEntity)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.visionai.v1.PersonalProtectiveEquipmentDetectionOutput.PersonIdentifiedBox"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// PPEIdentified box contains the location and the entity info of the PPE.
  public struct PPEIdentifiedBox: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// An unique id for this box.
    public var boxId: Swift.Int64 = Swift.Int64()

    /// Bounding Box in the normalized coordinates.
    public var normalizedBoundingBox:
      PersonalProtectiveEquipmentDetectionOutput.NormalizedBoundingBox? = nil

    /// Confidence score associated with this box.
    public var confidenceScore: Swift.Float = Swift.Float()

    /// PPE entity info.
    public var ppeEntity: PersonalProtectiveEquipmentDetectionOutput.PPEEntity? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PPEIdentifiedBox`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PPEIdentifiedBox().with { $0.boxId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let boxId = CodingKeys(stringValue: "boxId")
      static let normalizedBoundingBox = CodingKeys(stringValue: "normalizedBoundingBox")
      static let confidenceScore = CodingKeys(stringValue: "confidenceScore")
      static let ppeEntity = CodingKeys(stringValue: "ppeEntity")

      static let _knownKeys: Set<Swift.String> = [
        "boxId",
        "normalizedBoundingBox",
        "confidenceScore",
        "ppeEntity",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .boxId) {
        self.boxId = value
      }
      self.normalizedBoundingBox = try container.decodeIfPresent(
        PersonalProtectiveEquipmentDetectionOutput.NormalizedBoundingBox.self,
        forKey: .normalizedBoundingBox)
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .confidenceScore) {
        self.confidenceScore = value
      }
      self.ppeEntity = try container.decodeIfPresent(
        PersonalProtectiveEquipmentDetectionOutput.PPEEntity.self, forKey: .ppeEntity)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.boxId, forKey: .boxId)
      try container.encodeIfPresent(self.normalizedBoundingBox, forKey: .normalizedBoundingBox)
      try container.encode(self.confidenceScore, forKey: .confidenceScore)
      try container.encodeIfPresent(self.ppeEntity, forKey: .ppeEntity)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.visionai.v1.PersonalProtectiveEquipmentDetectionOutput.PPEIdentifiedBox"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Detected Person contains the detected person and their associated
  /// ppes and their protecting information.
  public struct DetectedPerson: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The id of detected person.
    public var personId: Swift.Int64 = Swift.Int64()

    /// The info of detected person identified box.
    public var detectedPersonIdentifiedBox:
      PersonalProtectiveEquipmentDetectionOutput.PersonIdentifiedBox? = nil

    /// The info of detected person associated ppe identified boxes.
    public var detectedPpeIdentifiedBoxes:
      [PersonalProtectiveEquipmentDetectionOutput.PPEIdentifiedBox] = []

    /// Coverage score for each body part.
    /// Coverage score for face.
    public var faceCoverageScore: Swift.Float? = nil

    /// Coverage score for eyes.
    public var eyesCoverageScore: Swift.Float? = nil

    /// Coverage score for head.
    public var headCoverageScore: Swift.Float? = nil

    /// Coverage score for hands.
    public var handsCoverageScore: Swift.Float? = nil

    /// Coverage score for body.
    public var bodyCoverageScore: Swift.Float? = nil

    /// Coverage score for feet.
    public var feetCoverageScore: Swift.Float? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `DetectedPerson`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DetectedPerson().with { $0.personId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let personId = CodingKeys(stringValue: "personId")
      static let detectedPersonIdentifiedBox = CodingKeys(
        stringValue: "detectedPersonIdentifiedBox")
      static let detectedPpeIdentifiedBoxes = CodingKeys(stringValue: "detectedPpeIdentifiedBoxes")
      static let faceCoverageScore = CodingKeys(stringValue: "faceCoverageScore")
      static let eyesCoverageScore = CodingKeys(stringValue: "eyesCoverageScore")
      static let headCoverageScore = CodingKeys(stringValue: "headCoverageScore")
      static let handsCoverageScore = CodingKeys(stringValue: "handsCoverageScore")
      static let bodyCoverageScore = CodingKeys(stringValue: "bodyCoverageScore")
      static let feetCoverageScore = CodingKeys(stringValue: "feetCoverageScore")

      static let _knownKeys: Set<Swift.String> = [
        "personId",
        "detectedPersonIdentifiedBox",
        "detectedPpeIdentifiedBoxes",
        "faceCoverageScore",
        "eyesCoverageScore",
        "headCoverageScore",
        "handsCoverageScore",
        "bodyCoverageScore",
        "feetCoverageScore",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .personId) {
        self.personId = value
      }
      self.detectedPersonIdentifiedBox = try container.decodeIfPresent(
        PersonalProtectiveEquipmentDetectionOutput.PersonIdentifiedBox.self,
        forKey: .detectedPersonIdentifiedBox)
      if let value = try container.decodeIfPresent(
        [PersonalProtectiveEquipmentDetectionOutput.PPEIdentifiedBox].self,
        forKey: .detectedPpeIdentifiedBoxes)
      {
        self.detectedPpeIdentifiedBoxes = value
      }
      self.faceCoverageScore = try container.decodeIfPresent(
        Swift.Float.self, forKey: .faceCoverageScore)
      self.eyesCoverageScore = try container.decodeIfPresent(
        Swift.Float.self, forKey: .eyesCoverageScore)
      self.headCoverageScore = try container.decodeIfPresent(
        Swift.Float.self, forKey: .headCoverageScore)
      self.handsCoverageScore = try container.decodeIfPresent(
        Swift.Float.self, forKey: .handsCoverageScore)
      self.bodyCoverageScore = try container.decodeIfPresent(
        Swift.Float.self, forKey: .bodyCoverageScore)
      self.feetCoverageScore = try container.decodeIfPresent(
        Swift.Float.self, forKey: .feetCoverageScore)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.personId, forKey: .personId)
      try container.encodeIfPresent(
        self.detectedPersonIdentifiedBox, forKey: .detectedPersonIdentifiedBox)
      try container.encode(self.detectedPpeIdentifiedBoxes, forKey: .detectedPpeIdentifiedBoxes)
      try container.encodeIfPresent(self.faceCoverageScore, forKey: .faceCoverageScore)
      try container.encodeIfPresent(self.eyesCoverageScore, forKey: .eyesCoverageScore)
      try container.encodeIfPresent(self.headCoverageScore, forKey: .headCoverageScore)
      try container.encodeIfPresent(self.handsCoverageScore, forKey: .handsCoverageScore)
      try container.encodeIfPresent(self.bodyCoverageScore, forKey: .bodyCoverageScore)
      try container.encodeIfPresent(self.feetCoverageScore, forKey: .feetCoverageScore)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.visionai.v1.PersonalProtectiveEquipmentDetectionOutput.DetectedPerson"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.PersonalProtectiveEquipmentDetectionOutput"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
