// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Message describing PersonalProtectiveEquipmentDetectionConfig.
public struct PersonalProtectiveEquipmentDetectionConfig: Codable, Equatable, GoogleWKT
    ._AnyPackable,
  Sendable
{
  /// Whether to enable face coverage detection.
  public var enableFaceCoverageDetection: Swift.Bool = Swift.Bool()

  /// Whether to enable head coverage detection.
  public var enableHeadCoverageDetection: Swift.Bool = Swift.Bool()

  /// Whether to enable hands coverage detection.
  public var enableHandsCoverageDetection: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PersonalProtectiveEquipmentDetectionConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PersonalProtectiveEquipmentDetectionConfig().with { $0.enableFaceCoverageDetection = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let enableFaceCoverageDetection = CodingKeys(stringValue: "enableFaceCoverageDetection")
    static let enableHeadCoverageDetection = CodingKeys(stringValue: "enableHeadCoverageDetection")
    static let enableHandsCoverageDetection = CodingKeys(
      stringValue: "enableHandsCoverageDetection")

    static let _knownKeys: Set<Swift.String> = [
      "enableFaceCoverageDetection",
      "enableHeadCoverageDetection",
      "enableHandsCoverageDetection",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .enableFaceCoverageDetection)
    {
      self.enableFaceCoverageDetection = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .enableHeadCoverageDetection)
    {
      self.enableHeadCoverageDetection = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .enableHandsCoverageDetection)
    {
      self.enableHandsCoverageDetection = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.enableFaceCoverageDetection, forKey: .enableFaceCoverageDetection)
    try container.encode(self.enableHeadCoverageDetection, forKey: .enableHeadCoverageDetection)
    try container.encode(self.enableHandsCoverageDetection, forKey: .enableHandsCoverageDetection)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `PersonalProtectiveEquipmentDetectionConfig`: `"type.googleapis.com/google.cloud.visionai.v1.PersonalProtectiveEquipmentDetectionConfig"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.PersonalProtectiveEquipmentDetectionConfig"
  }

  /// Initialize an instance of `PersonalProtectiveEquipmentDetectionConfig` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.visionai.v1.PersonalProtectiveEquipmentDetectionConfig"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `PersonalProtectiveEquipmentDetectionConfig` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
