// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Message describing ProductRecognizerConfig.
public struct ProductRecognizerConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The resource name of retail endpoint to use.
  public var retailEndpoint: Swift.String = Swift.String()

  /// Confidence threshold to filter detection results. If not set, a system
  /// default value will be used.
  public var recognitionConfidenceThreshold: Swift.Float = Swift.Float()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ProductRecognizerConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ProductRecognizerConfig().with { $0.retailEndpoint = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let retailEndpoint = CodingKeys(stringValue: "retailEndpoint")
    static let recognitionConfidenceThreshold = CodingKeys(
      stringValue: "recognitionConfidenceThreshold")

    static let _knownKeys: Set<Swift.String> = [
      "retailEndpoint",
      "recognitionConfidenceThreshold",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .retailEndpoint) {
      self.retailEndpoint = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Float.self, forKey: .recognitionConfidenceThreshold)
    {
      self.recognitionConfidenceThreshold = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.retailEndpoint, forKey: .retailEndpoint)
    try container.encode(
      self.recognitionConfidenceThreshold, forKey: .recognitionConfidenceThreshold)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.ProductRecognizerConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
