// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Control message for a ReceiveEventsResponse.
public struct ReceiveEventsControlResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Possible control messages.
  public var control: ControlOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ReceiveEventsControlResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReceiveEventsControlResponse().with { $0.heartbeat = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let heartbeat = CodingKeys(stringValue: "heartbeat")
    static let writesDoneRequest = CodingKeys(stringValue: "writesDoneRequest")

    static let _knownKeys: Set<Swift.String> = [
      "heartbeat",
      "writesDoneRequest",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var control: ControlOneOf? = nil
    let controlCheckAndSet = {
      if control != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'control'"))
      }
      control = $0
    }
    if let heartbeat = try container.decodeIfPresent(Swift.Bool.self, forKey: .heartbeat) {
      try controlCheckAndSet(.heartbeat(heartbeat))
    }
    if let writesDoneRequest = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .writesDoneRequest)
    {
      try controlCheckAndSet(.writesDoneRequest(writesDoneRequest))
    }
    self.control = control
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.control {
      switch choice {
      case .heartbeat(let value):
        try container.encode(value, forKey: .heartbeat)
      case .writesDoneRequest(let value):
        try container.encode(value, forKey: .writesDoneRequest)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Possible control messages.
  public enum ControlOneOf: Codable, Equatable, Sendable {
    /// A server heartbeat.
    case heartbeat(Swift.Bool)
    /// A request to the receiver to complete any final writes followed by a
    /// `WritesDone`; e.g. issue any final `CommitRequest`s.
    ///
    /// May be ignored if `WritesDone` has already been issued at any point
    /// prior to receiving this message.
    ///
    /// If `WritesDone` does not get issued, then the server will forcefully
    /// cancel the connection, and the receiver will likely receive an
    /// uninformative after `Read` returns `false` and `Finish` is called.
    case writesDoneRequest(Swift.Bool)
  }

  /// The type URL for `ReceiveEventsControlResponse`: `"type.googleapis.com/google.cloud.visionai.v1.ReceiveEventsControlResponse"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.ReceiveEventsControlResponse"
  }

  /// Initialize an instance of `ReceiveEventsControlResponse` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.visionai.v1.ReceiveEventsControlResponse"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `ReceiveEventsControlResponse` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
