// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for receiving packets.
public struct ReceivePacketsRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Possible request types from the client.
  public var request: RequestOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ReceivePacketsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReceivePacketsRequest().with { $0.setupRequest = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let setupRequest = CodingKeys(stringValue: "setupRequest")
    static let commitRequest = CodingKeys(stringValue: "commitRequest")

    static let _knownKeys: Set<Swift.String> = [
      "setupRequest",
      "commitRequest",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var request: RequestOneOf? = nil
    let requestCheckAndSet = {
      if request != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'request'"))
      }
      request = $0
    }
    if let setupRequest = try container.decodeIfPresent(
      ReceivePacketsRequest.SetupRequest.self, forKey: .setupRequest)
    {
      try requestCheckAndSet(.setupRequest(setupRequest))
    }
    if let commitRequest = try container.decodeIfPresent(CommitRequest.self, forKey: .commitRequest)
    {
      try requestCheckAndSet(.commitRequest(commitRequest))
    }
    self.request = request
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.request {
      switch choice {
      case .setupRequest(let value):
        try container.encode(value, forKey: .setupRequest)
      case .commitRequest(let value):
        try container.encode(value, forKey: .commitRequest)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The message specifying the initial settings for the ReceivePackets session.
  public struct SetupRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The configurations that specify where packets are retrieved.
    public var metadata: RequestMetadata? = nil

    /// A name for the receiver to self-identify.
    ///
    /// This is used to keep track of a receiver's read progress.
    public var receiver: Swift.String = Swift.String()

    /// The maximum duration of server silence before the client determines the
    /// server unreachable.
    ///
    /// The client must either receive a `Packet` or a heart beat message before
    /// this duration expires; otherwise, the client will automatically cancel
    /// the current connection and retry.
    public var heartbeatInterval: GoogleWKT.WKTDuration? = nil

    /// The grace period after which a `writes_done_request` is issued, that a
    /// `WritesDone` is expected from the client.
    ///
    /// The server is free to cancel the RPC should this expire.
    ///
    /// A system default will be chosen if unset.
    public var writesDoneGracePeriod: GoogleWKT.WKTDuration? = nil

    /// The mode in which the consumer reads messages.
    public var consumerMode: ConsumerModeOneOf? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SetupRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SetupRequest().with { $0.eagerReceiveMode = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let eagerReceiveMode = CodingKeys(stringValue: "eagerReceiveMode")
      static let controlledReceiveMode = CodingKeys(stringValue: "controlledReceiveMode")
      static let metadata = CodingKeys(stringValue: "metadata")
      static let receiver = CodingKeys(stringValue: "receiver")
      static let heartbeatInterval = CodingKeys(stringValue: "heartbeatInterval")
      static let writesDoneGracePeriod = CodingKeys(stringValue: "writesDoneGracePeriod")

      static let _knownKeys: Set<Swift.String> = [
        "eagerReceiveMode",
        "controlledReceiveMode",
        "metadata",
        "receiver",
        "heartbeatInterval",
        "writesDoneGracePeriod",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.metadata = try container.decodeIfPresent(RequestMetadata.self, forKey: .metadata)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .receiver) {
        self.receiver = value
      }
      self.heartbeatInterval = try container.decodeIfPresent(
        GoogleWKT.WKTDuration.self, forKey: .heartbeatInterval)
      self.writesDoneGracePeriod = try container.decodeIfPresent(
        GoogleWKT.WKTDuration.self, forKey: .writesDoneGracePeriod)

      var consumerMode: ConsumerModeOneOf? = nil
      let consumerModeCheckAndSet = {
        if consumerMode != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'consumerMode'"))
        }
        consumerMode = $0
      }
      if let eagerReceiveMode = try container.decodeIfPresent(
        EagerMode.self, forKey: .eagerReceiveMode)
      {
        try consumerModeCheckAndSet(.eagerReceiveMode(eagerReceiveMode))
      }
      if let controlledReceiveMode = try container.decodeIfPresent(
        ControlledMode.self, forKey: .controlledReceiveMode)
      {
        try consumerModeCheckAndSet(.controlledReceiveMode(controlledReceiveMode))
      }
      self.consumerMode = consumerMode
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.metadata, forKey: .metadata)
      try container.encode(self.receiver, forKey: .receiver)
      try container.encodeIfPresent(self.heartbeatInterval, forKey: .heartbeatInterval)
      try container.encodeIfPresent(self.writesDoneGracePeriod, forKey: .writesDoneGracePeriod)

      if let choice = self.consumerMode {
        switch choice {
        case .eagerReceiveMode(let value):
          try container.encode(value, forKey: .eagerReceiveMode)
        case .controlledReceiveMode(let value):
          try container.encode(value, forKey: .controlledReceiveMode)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The mode in which the consumer reads messages.
    public enum ConsumerModeOneOf: Codable, Equatable, Sendable {
      /// Options for configuring eager mode.
      indirect case eagerReceiveMode(EagerMode)
      /// Options for configuring controlled mode.
      indirect case controlledReceiveMode(ControlledMode)
    }

    /// The type URL for `SetupRequest`: `"type.googleapis.com/google.cloud.visionai.v1.ReceivePacketsRequest.SetupRequest"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.visionai.v1.ReceivePacketsRequest.SetupRequest"
    }

    /// Initialize an instance of `SetupRequest` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.visionai.v1.ReceivePacketsRequest.SetupRequest"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `SetupRequest` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Possible request types from the client.
  public enum RequestOneOf: Codable, Equatable, Sendable {
    /// The request to setup the initial state of session.
    ///
    /// The client must send and only send this as the first message.
    indirect case setupRequest(ReceivePacketsRequest.SetupRequest)
    /// This request checkpoints the consumer's read progress.
    indirect case commitRequest(CommitRequest)
  }

  /// The type URL for `ReceivePacketsRequest`: `"type.googleapis.com/google.cloud.visionai.v1.ReceivePacketsRequest"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.ReceivePacketsRequest"
  }

  /// Initialize an instance of `ReceivePacketsRequest` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.visionai.v1.ReceivePacketsRequest"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `ReceivePacketsRequest` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
