// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// ResourceSpec collects a set of resources that can
/// be used to specify requests and requirements.
///
/// Note: Highly experimental as this can be runtime dependent.
/// Can use the "extras" field to experiment first before trying
/// to abstract it.
public struct ResourceSpecification: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// CPU specification.
  ///
  /// Examples:
  /// "100m", "0.5", "1", "2", ... correspond to
  /// 0.1, half, 1, or 2 cpus.
  ///
  /// Leave empty to let the system decide.
  ///
  /// Note that this does *not* determine the cpu vender/make,
  /// or its underlying clock speed and specific SIMD features.
  /// It is only the amount time it requires in timeslicing.
  public var cpu: Swift.String = Swift.String()

  /// CPU limit.
  ///
  /// Examples:
  /// "100m", "0.5", "1", "2", ... correspond to
  /// 0.1, half, 1, or 2 cpus.
  ///
  /// Leave empty to indicate no limit.
  public var cpuLimits: Swift.String = Swift.String()

  /// Memory specification (in bytes).
  ///
  /// Examples:
  /// "128974848", "129e6", "129M", "123Mi", ... correspond to
  /// 128974848 bytes, 129000000 bytes, 129 mebibytes, 123 megabytes.
  ///
  /// Leave empty to let the system decide.
  public var memory: Swift.String = Swift.String()

  /// Memory usage limits.
  ///
  /// Examples:
  /// "128974848", "129e6", "129M", "123Mi", ... correspond to
  /// 128974848 bytes, 129000000 bytes, 129 mebibytes, 123 megabytes.
  ///
  /// Leave empty to indicate no limit.
  public var memoryLimits: Swift.String = Swift.String()

  /// Number of gpus.
  public var gpus: Swift.Int32 = Swift.Int32()

  /// The maximum latency that this operator may use to process an element.
  ///
  /// If non positive, then a system default will be used.
  /// Operator developers should arrange for the system compute resources to be
  /// aligned with this latency budget; e.g. if you want a ML model to produce
  /// results within 500ms, then you should make sure you request enough
  /// cpu/gpu/memory to achieve that.
  public var latencyBudgetMs: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ResourceSpecification`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ResourceSpecification().with { $0.cpu = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let cpu = CodingKeys(stringValue: "cpu")
    static let cpuLimits = CodingKeys(stringValue: "cpuLimits")
    static let memory = CodingKeys(stringValue: "memory")
    static let memoryLimits = CodingKeys(stringValue: "memoryLimits")
    static let gpus = CodingKeys(stringValue: "gpus")
    static let latencyBudgetMs = CodingKeys(stringValue: "latencyBudgetMs")

    static let _knownKeys: Set<Swift.String> = [
      "cpu",
      "cpuLimits",
      "memory",
      "memoryLimits",
      "gpus",
      "latencyBudgetMs",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cpu) {
      self.cpu = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cpuLimits) {
      self.cpuLimits = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .memory) {
      self.memory = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .memoryLimits) {
      self.memoryLimits = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .gpus) {
      self.gpus = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .latencyBudgetMs) {
      self.latencyBudgetMs = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.cpu, forKey: .cpu)
    try container.encode(self.cpuLimits, forKey: .cpuLimits)
    try container.encode(self.memory, forKey: .memory)
    try container.encode(self.memoryLimits, forKey: .memoryLimits)
    try container.encode(self.gpus, forKey: .gpus)
    try container.encode(self.latencyBudgetMs, forKey: .latencyBudgetMs)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `ResourceSpecification`: `"type.googleapis.com/google.cloud.visionai.v1.ResourceSpecification"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.ResourceSpecification"
  }

  /// Initialize an instance of `ResourceSpecification` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.visionai.v1.ResourceSpecification"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `ResourceSpecification` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
