// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Message describing the Stream object. The Stream and the Event resources are
/// many to many; i.e., each Stream resource can associate to many Event
/// resources and each Event resource can associate to many Stream resources.
public struct Stream: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Name of the resource.
  public var name: Swift.String = Swift.String()

  /// Output only. The create timestamp.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The update timestamp.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Labels as key value pairs.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Annotations to allow clients to store small amounts of arbitrary data.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// The display name for the stream resource.
  public var displayName: Swift.String = Swift.String()

  /// Whether to enable the HLS playback service on this stream.
  public var enableHlsPlayback: Swift.Bool = Swift.Bool()

  /// The name of the media warehouse asset for long term storage of stream data.
  /// Format: projects/${p_id}/locations/${l_id}/corpora/${c_id}/assets/${a_id}
  /// Remain empty if the media warehouse storage is not needed for the stream.
  public var mediaWarehouseAsset: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Stream`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Stream().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let annotations = CodingKeys(stringValue: "annotations")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let enableHlsPlayback = CodingKeys(stringValue: "enableHlsPlayback")
    static let mediaWarehouseAsset = CodingKeys(stringValue: "mediaWarehouseAsset")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "labels",
      "annotations",
      "displayName",
      "enableHlsPlayback",
      "mediaWarehouseAsset",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .annotations)
    {
      self.annotations = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enableHlsPlayback) {
      self.enableHlsPlayback = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .mediaWarehouseAsset) {
      self.mediaWarehouseAsset = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.annotations, forKey: .annotations)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.enableHlsPlayback, forKey: .enableHlsPlayback)
    try container.encode(self.mediaWarehouseAsset, forKey: .mediaWarehouseAsset)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `Stream`: `"type.googleapis.com/google.cloud.visionai.v1.Stream"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.Stream"
  }

  /// Initialize an instance of `Stream` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.visionai.v1.Stream"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `Stream` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
