// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// message about annotations about Vision AI stream resource.
public struct StreamAnnotation: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// ID of the annotation. It must be unique when used in the certain context.
  /// For example, all the annotations to one input streams of a Vision AI
  /// application.
  public var id: Swift.String = Swift.String()

  /// User-friendly name for the annotation.
  public var displayName: Swift.String = Swift.String()

  /// The Vision AI stream resource name.
  public var sourceStream: Swift.String = Swift.String()

  /// The actual type of Annotation.
  public var type: StreamAnnotationType = StreamAnnotationType()

  public var annotationPayload: AnnotationPayloadOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `StreamAnnotation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StreamAnnotation().with { $0.activeZone = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let activeZone = CodingKeys(stringValue: "activeZone")
    static let crossingLine = CodingKeys(stringValue: "crossingLine")
    static let id = CodingKeys(stringValue: "id")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let sourceStream = CodingKeys(stringValue: "sourceStream")
    static let type = CodingKeys(stringValue: "type")

    static let _knownKeys: Set<Swift.String> = [
      "activeZone",
      "crossingLine",
      "id",
      "displayName",
      "sourceStream",
      "type",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
      self.id = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourceStream) {
      self.sourceStream = value
    }
    if let value = try container.decodeIfPresent(StreamAnnotationType.self, forKey: .type) {
      self.type = value
    }

    var annotationPayload: AnnotationPayloadOneOf? = nil
    let annotationPayloadCheckAndSet = {
      if annotationPayload != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'annotationPayload'"))
      }
      annotationPayload = $0
    }
    if let activeZone = try container.decodeIfPresent(NormalizedPolygon.self, forKey: .activeZone) {
      try annotationPayloadCheckAndSet(.activeZone(activeZone))
    }
    if let crossingLine = try container.decodeIfPresent(
      NormalizedPolyline.self, forKey: .crossingLine)
    {
      try annotationPayloadCheckAndSet(.crossingLine(crossingLine))
    }
    self.annotationPayload = annotationPayload
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.id, forKey: .id)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.sourceStream, forKey: .sourceStream)
    try container.encode(self.type, forKey: .type)

    if let choice = self.annotationPayload {
      switch choice {
      case .activeZone(let value):
        try container.encode(value, forKey: .activeZone)
      case .crossingLine(let value):
        try container.encode(value, forKey: .crossingLine)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public enum AnnotationPayloadOneOf: Codable, Equatable, Sendable {
    /// Annotation for type ACTIVE_ZONE
    indirect case activeZone(NormalizedPolygon)
    /// Annotation for type CROSSING_LINE
    indirect case crossingLine(NormalizedPolyline)
  }

  /// The type URL for `StreamAnnotation`: `"type.googleapis.com/google.cloud.visionai.v1.StreamAnnotation"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.StreamAnnotation"
  }

  /// Initialize an instance of `StreamAnnotation` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.visionai.v1.StreamAnnotation"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `StreamAnnotation` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
