// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Prediction output format for Video Object Tracking.
public struct VideoObjectTrackingPredictionResult: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The beginning, inclusive, of the video's time segment in which the
  /// current identifications happens.
  public var segmentStartTime: GoogleWKT.WKTTimestamp? = nil

  /// The end, inclusive, of the video's time segment in which the current
  /// identifications happen. Particularly, if the end is the same as the start,
  /// it means the identifications happen on a specific video frame.
  public var segmentEndTime: GoogleWKT.WKTTimestamp? = nil

  /// All of the objects detected in the specified time range.
  public var objects: [VideoObjectTrackingPredictionResult.DetectedObject] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `VideoObjectTrackingPredictionResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VideoObjectTrackingPredictionResult().with { $0.segmentStartTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let segmentStartTime = CodingKeys(stringValue: "segmentStartTime")
    static let segmentEndTime = CodingKeys(stringValue: "segmentEndTime")
    static let objects = CodingKeys(stringValue: "objects")

    static let _knownKeys: Set<Swift.String> = [
      "segmentStartTime",
      "segmentEndTime",
      "objects",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.segmentStartTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .segmentStartTime)
    self.segmentEndTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .segmentEndTime)
    if let value = try container.decodeIfPresent(
      [VideoObjectTrackingPredictionResult.DetectedObject].self, forKey: .objects)
    {
      self.objects = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.segmentStartTime, forKey: .segmentStartTime)
    try container.encodeIfPresent(self.segmentEndTime, forKey: .segmentEndTime)
    try container.encode(self.objects, forKey: .objects)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Boundingbox for detected object. I.e. the rectangle over the video frame
  /// pinpointing the found AnnotationSpec. The coordinates are relative to the
  /// frame size, and the point 0,0 is in the top left of the frame.
  public struct BoundingBox: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The leftmost coordinate of the bounding box.
    public var xMin: Swift.Float = Swift.Float()

    /// The rightmost coordinate of the bounding box.
    public var xMax: Swift.Float = Swift.Float()

    /// The topmost coordinate of the bounding box.
    public var yMin: Swift.Float = Swift.Float()

    /// The bottommost coordinate of the bounding box.
    public var yMax: Swift.Float = Swift.Float()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `BoundingBox`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BoundingBox().with { $0.xMin = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let xMin = CodingKeys(stringValue: "xMin")
      static let xMax = CodingKeys(stringValue: "xMax")
      static let yMin = CodingKeys(stringValue: "yMin")
      static let yMax = CodingKeys(stringValue: "yMax")

      static let _knownKeys: Set<Swift.String> = [
        "xMin",
        "xMax",
        "yMin",
        "yMax",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .xMin) {
        self.xMin = value
      }
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .xMax) {
        self.xMax = value
      }
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .yMin) {
        self.yMin = value
      }
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .yMax) {
        self.yMax = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.xMin, forKey: .xMin)
      try container.encode(self.xMax, forKey: .xMax)
      try container.encode(self.yMin, forKey: .yMin)
      try container.encode(self.yMax, forKey: .yMax)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.visionai.v1.VideoObjectTrackingPredictionResult.BoundingBox"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Each DetectedObject is one particular identification of an object
  /// specified with the AnnotationSpec id and display_name, the bounding box,
  /// the associated confidence score and the corresponding track_id.
  public struct DetectedObject: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The resource ID of the AnnotationSpec that had been identified.
    public var id: Swift.String = Swift.String()

    /// The display name of the AnnotationSpec that had been identified.
    public var displayName: Swift.String = Swift.String()

    /// Boundingbox.
    public var boundingBox: VideoObjectTrackingPredictionResult.BoundingBox? = nil

    /// The Model's confidence in correction of this identification, higher
    /// value means higher confidence.
    public var confidence: Swift.Float = Swift.Float()

    /// The same object may be identified on muitiple frames which are typical
    /// adjacent. The set of frames where a particular object has been detected
    /// form a track. This track_id can be used to trace down all frames for an
    /// detected object.
    public var trackId: Swift.Int64 = Swift.Int64()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `DetectedObject`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DetectedObject().with { $0.id = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let id = CodingKeys(stringValue: "id")
      static let displayName = CodingKeys(stringValue: "displayName")
      static let boundingBox = CodingKeys(stringValue: "boundingBox")
      static let confidence = CodingKeys(stringValue: "confidence")
      static let trackId = CodingKeys(stringValue: "trackId")

      static let _knownKeys: Set<Swift.String> = [
        "id",
        "displayName",
        "boundingBox",
        "confidence",
        "trackId",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
        self.id = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
        self.displayName = value
      }
      self.boundingBox = try container.decodeIfPresent(
        VideoObjectTrackingPredictionResult.BoundingBox.self, forKey: .boundingBox)
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .confidence) {
        self.confidence = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .trackId) {
        self.trackId = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.id, forKey: .id)
      try container.encode(self.displayName, forKey: .displayName)
      try container.encodeIfPresent(self.boundingBox, forKey: .boundingBox)
      try container.encode(self.confidence, forKey: .confidence)
      try container.encode(self.trackId, forKey: .trackId)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.visionai.v1.VideoObjectTrackingPredictionResult.DetectedObject"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.visionai.v1.VideoObjectTrackingPredictionResult"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
